import { ScheduledReportsQueryDto } from '../../common/dto/resource-query.dto';
import {
  Controller,
  Get,
  Post,
  Patch,
  Delete,
  Body,
  Param,
  Query,
  Res,
  StreamableFile,
  UseGuards,
} from '@nestjs/common';
import { Response } from 'express';
import { ApiTags, ApiBearerAuth } from '@nestjs/swagger';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { PermissionsGuard } from '../../common/guards/permissions.guard';
import { RequirePermissions } from '../../common/decorators/require-permissions.decorator';
import { CurrentUser, AuthUser } from '../../common/decorators/current-user.decorator';
import { AgentExcluded } from '../../common/decorators/agent-excluded.decorator';
import { ScheduledReportsService } from './scheduled-reports.service';
import { CreateScheduledReportDto } from './dto/create-scheduled-report.dto';
import { UpdateScheduledReportDto } from './dto/update-scheduled-report.dto';

@ApiTags('Scheduled Reports')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard, PermissionsGuard)
@Controller('bi/scheduled-reports')
export class ScheduledReportsController {
  constructor(private readonly service: ScheduledReportsService) {}

  @Post()
  @RequirePermissions('scheduled_reports.manage')
  create(@Body() dto: CreateScheduledReportDto, @CurrentUser() user: AuthUser) {
    return this.service.create(dto, user);
  }

  @Get()
  @RequirePermissions('scheduled_reports.view')
  findAll(@CurrentUser() user: AuthUser, @Query() query: ScheduledReportsQueryDto) {
    return this.service.findAll(user, query);
  }

  /**
   * Stream the file generated by a scheduled run (stored base64 in
   * ReportRun.resultSummary). Declared above the ':id' routes so the static
   * 'runs' segment can never be captured as a schedule id.
   */
  @Get('runs/:runId/download')
  @AgentExcluded('read_writes_audit_ledger')
  @RequirePermissions('scheduled_reports.view')
  async downloadRun(
    @Param('runId') runId: string,
    @CurrentUser() user: AuthUser,
    @Res({ passthrough: true }) res: Response,
  ) {
    const file = await this.service.downloadRun(runId, user);
    const safeFilename = file.filename.replace(/[\\"\r\n]/g, '_');
    res.set({
      'Content-Type': file.mimeType,
      'Content-Disposition': `attachment; filename="${safeFilename}"; filename*=UTF-8''${encodeURIComponent(file.filename)}`,
      'X-Content-Type-Options': 'nosniff',
    });
    return new StreamableFile(file.content);
  }

  @Get(':id/runs')
  @AgentExcluded('query_schema_not_strict')
  @RequirePermissions('scheduled_reports.view')
  listRuns(@Param('id') id: string, @CurrentUser() user: AuthUser, @Query() query: any) {
    return this.service.listRuns(id, user, query);
  }

  @Get(':id')
  @RequirePermissions('scheduled_reports.view')
  findOne(@Param('id') id: string, @CurrentUser() user: AuthUser) {
    return this.service.findOne(id, user);
  }

  @Patch(':id')
  @RequirePermissions('scheduled_reports.manage')
  update(
    @Param('id') id: string,
    @Body() dto: UpdateScheduledReportDto,
    @CurrentUser() user: AuthUser,
  ) {
    return this.service.update(id, dto, user);
  }

  @Post(':id/run')
  @RequirePermissions('scheduled_reports.run')
  run(@Param('id') id: string, @CurrentUser() user: AuthUser) {
    return this.service.run(id, user);
  }

  @Patch(':id/activate')
  @RequirePermissions('scheduled_reports.manage')
  activate(@Param('id') id: string, @CurrentUser() user: AuthUser) {
    return this.service.activate(id, user);
  }

  @Patch(':id/deactivate')
  @RequirePermissions('scheduled_reports.manage')
  deactivate(@Param('id') id: string, @CurrentUser() user: AuthUser) {
    return this.service.deactivate(id, user);
  }

  @Delete(':id')
  @RequirePermissions('scheduled_reports.manage')
  remove(@Param('id') id: string, @CurrentUser() user: AuthUser) {
    return this.service.remove(id, user);
  }
}
