import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../../prisma/prisma.service';
import { JobContext, JobHandlerRegistry, JobResult } from '../job-handler.registry';

@Injectable()
export class RentInvoiceGenerationJobHandler implements OnModuleInit {
  private readonly logger = new Logger(RentInvoiceGenerationJobHandler.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly registry: JobHandlerRegistry,
  ) {}

  onModuleInit(): void {
    this.registry.register('RENT_INVOICE_GENERATION', (ctx) => this.handle(ctx));
  }

  private async handle(ctx: JobContext): Promise<JobResult> {
    const companyId = ctx.payload.companyId as string | undefined;
    const leaseAgreementId = ctx.payload.leaseAgreementId as string | undefined;
    const asOf = ctx.payload.asOf ? new Date(ctx.payload.asOf as string) : new Date();
    const dryRun = Boolean(ctx.payload.dryRun);

    const leases = await this.prisma.leaseAgreement.findMany({
      where: {
        deletedAt: null,
        status: 'ACTIVE' as any,
        ...(companyId ? { companyId } : {}),
        ...(leaseAgreementId ? { id: leaseAgreementId } : {}),
        OR: [{ endDate: null }, { endDate: { gte: asOf } }],
      },
      include: {
        invoices: {
          where: { deletedAt: null },
          orderBy: { billingPeriodEnd: 'desc' },
          take: 1,
        },
      },
    });

    const created: string[] = [];
    const skipped: Array<{ leaseId: string; reason: string }> = [];

    for (const lease of leases) {
      const last = lease.invoices[0];
      const nextStart = last
        ? this.addOneFrequency(last.billingPeriodEnd, lease.billingFrequency)
        : new Date(lease.startDate);
      const nextEnd = this.endOfFrequency(nextStart, lease.billingFrequency);

      if (nextStart > asOf) {
        skipped.push({ leaseId: lease.id, reason: 'next period not yet due' });
        continue;
      }

      if (dryRun) {
        created.push(`would-create:${lease.id}`);
        continue;
      }

      try {
        const rentInvoiceNumber = `RI-${nextStart.getFullYear()}-${String(
          nextStart.getMonth() + 1,
        ).padStart(2, '0')}-${lease.leaseCode}`;
        const existing = await this.prisma.rentInvoice.findFirst({
          where: { companyId: lease.companyId, rentInvoiceNumber },
          select: { id: true },
        });
        if (existing) {
          skipped.push({ leaseId: lease.id, reason: 'invoice already exists for period' });
          continue;
        }

        const rentAmount = new Prisma.Decimal(lease.rentAmount);
        await this.prisma.rentInvoice.create({
          data: {
            rentInvoiceNumber,
            companyId: lease.companyId,
            propertyId: lease.propertyId,
            rentalUnitId: lease.rentalUnitId,
            tenantId: lease.tenantId,
            leaseAgreementId: lease.id,
            invoiceDate: nextStart,
            billingPeriodStart: nextStart,
            billingPeriodEnd: nextEnd,
            dueDate: nextEnd,
            rentAmount,
            totalAmount: rentAmount,
            outstandingAmount: rentAmount,
            currency: lease.currency ?? 'TZS',
            status: 'DRAFT' as any,
            createdById: lease.createdById,
            notes: `Auto-generated by recurring job for ${lease.leaseCode}`,
          },
        });
        created.push(lease.id);
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        this.logger.error(`Failed to generate rent invoice for lease ${lease.id}: ${message}`);
        skipped.push({ leaseId: lease.id, reason: message });
      }
    }

    return {
      data: {
        scanned: leases.length,
        createdCount: created.length,
        skippedCount: skipped.length,
        dryRun,
        asOf: asOf.toISOString(),
      },
    };
  }

  private addOneFrequency(from: Date, frequency: string | null): Date {
    const next = new Date(from);
    switch (frequency) {
      case 'DAILY':
        next.setDate(next.getDate() + 1);
        break;
      case 'WEEKLY':
        next.setDate(next.getDate() + 7);
        break;
      case 'QUARTERLY':
        next.setMonth(next.getMonth() + 3);
        break;
      case 'YEARLY':
        next.setFullYear(next.getFullYear() + 1);
        break;
      case 'MONTHLY':
      case 'CUSTOM':
      default:
        next.setMonth(next.getMonth() + 1);
        break;
    }
    return next;
  }

  private endOfFrequency(start: Date, frequency: string | null): Date {
    const nextStart = this.addOneFrequency(start, frequency);
    return new Date(nextStart.getTime() - 24 * 60 * 60 * 1000);
  }
}
