export const meta = {
  name: 'itemba-apply-fixes',
  description: 'Apply minimal, production-safe fixes for verified ITEMBA-R audit findings, partitioned by module (disjoint files), with a per-batch recheck pass',
  phases: [
    { title: 'Fix', detail: 'module-partitioned agents apply narrowing/additive fixes to disjoint files' },
    { title: 'Recheck', detail: 're-read each batch files to confirm edits compile and address the finding' },
  ],
}

const REPO = `ITEMBA-R monorepo, root "c:/projects/Actual Projects/itemba-r". Backend: NestJS 11 + Prisma 5 (backend/src). Frontend: Next.js 14 (frontend/src). This is a LIVE production app. The full remediation guidance for every finding ID is in AUDIT_FIX_SUGGESTIONS.md and the detail is in AUDIT_FINDINGS.md at the repo root — grep for the exact ID (e.g. "ITMB-001") to read its fix before editing.`

const SAFETY = `\n\nABSOLUTE RULES:
- Apply ONLY the fixes for the finding IDs assigned to you, and edit ONLY the files listed for your batch. Do not touch any other file (other agents own them concurrently).
- Fixes must be MINIMAL and NARROWING/ADDITIVE: add missing access checks, validation, transactions, server-side computation, or expiry. Do NOT change public API response shapes, do NOT rename things, do NOT refactor unrelated code. Legitimate same-company behaviour must be unchanged.
- The code MUST still compile (TypeScript). When you add a dependency (e.g. CompanyScopeService), also add the import and constructor injection; when a service method gains an AuthUser param, update its module providers if needed and update the controller to pass @CurrentUser() user (import CurrentUser + AuthUser from common/decorators/current-user.decorator). Verify the module that provides the service already imports CommonModule/PrismaModule as used by sibling modules.
- Follow EXISTING patterns in the codebase. The canonical tenant-isolation pattern is in backend/src/modules/customer-statements/customer-statements.service.ts (inject CompanyScopeService; in findOne load the record then await this.companyScope.assertCanAccessCompany(user, record.companyId); use AccessLevel.WRITE for mutations; controllers pass @CurrentUser() user). For company-scoped list filters use applyCompanyScopeWhere / companyWhereFor.
- If a fix would require a DB migration, would change response shape, would break decryption/validation of EXISTING stored data, or you are not confident it is correct and safe, SKIP it and report status 'skipped' with a clear reason. Do NOT guess on financial logic.
- Do NOT run any build, test, npm, or git command. Just edit files and re-read them to confirm correctness.
- Read each file before editing; make surgical edits; re-read after to confirm imports/wiring are consistent.
Report each assigned ID with: id, status ('fixed'|'partial'|'skipped'), the files you changed, and a one-line note.`

const REPORT_SCHEMA = {
  type: 'object', additionalProperties: false,
  properties: {
    reports: {
      type: 'array',
      items: {
        type: 'object', additionalProperties: false,
        properties: {
          id: { type: 'string' },
          status: { type: 'string', enum: ['fixed', 'partial', 'skipped'] },
          files: { type: 'array', items: { type: 'string' } },
          note: { type: 'string' },
        },
        required: ['id', 'status', 'note'],
      },
    },
  },
  required: ['reports'],
}

const BATCHES = [
  { key: 'intercompany', ids: ['ITMB-001'], files: ['backend/src/modules/intercompany-transactions/intercompany-transactions.service.ts', 'backend/src/modules/intercompany-transactions/intercompany-transactions.controller.ts', 'backend/src/modules/intercompany-transactions/intercompany-transactions.module.ts'], focus: 'Add CompanyScopeService; scope findAll to accessible companies; assert access (BOTH from/to companies for create/update/post) on findOne and every id-based mutation incl. post().' },
  { key: 'restaurant', ids: ['ITMB-002', 'ITMB-038', 'ITMB-073'], files: ['backend/src/modules/restaurant-orders/restaurant-orders.service.ts', 'backend/src/modules/restaurant-orders/restaurant-orders.controller.ts', 'backend/src/modules/restaurant-orders/dto/create-restaurant-order.dto.ts'], focus: 'Remove client monetary/status fields from create DTO; compute subtotal/tax/total server-side from lines; init paidAmount=0/outstanding=total/paymentStatus=UNPAID; add company-scope assert on create/findOne.' },
  { key: 'sales-orders', ids: ['ITMB-003', 'ITMB-041'], files: ['backend/src/modules/sales-orders/sales-orders.service.ts', 'backend/src/modules/sales-orders/dto/create-sales-order.dto.ts'], focus: 'Recompute line tax/discount/totals server-side; add @Min(0.0001) quantity, @Min(0) price/discount validators. (Leave credit-limit ITMB-046 to another agent.)' },
  { key: 'auth', ids: ['ITMB-005', 'ITMB-050', 'ITMB-051', 'ITMB-090', 'ITMB-098'], files: ['backend/src/modules/auth/auth.module.ts', 'backend/src/modules/auth/auth.service.ts', 'backend/src/modules/auth/two-factor.service.ts'], focus: 'ITMB-005: force a finite access-token TTL (fall back to 15m when configured non-expiring) so access tokens always carry exp. ITMB-051: in completeLogin2FA re-check user.lockedUntil and count 2FA failures toward lockout. ITMB-098: persist last accepted TOTP step to prevent replay. ITMB-090: only if trivial. ITMB-050: back the per-email lockout with the configured cache if straightforward, else SKIP. DO NOT implement refresh-token rotation (ITMB-006 is deferred) and do not change refresh behaviour.' },
  { key: 'depreciation', ids: ['ITMB-009', 'ITMB-010', 'ITMB-056', 'ITMB-100'], files: ['backend/src/modules/depreciation/depreciation.service.ts', 'backend/src/modules/depreciation/depreciation.controller.ts', 'backend/src/modules/depreciation/depreciation.module.ts'], focus: 'Inject CompanyScopeService; scope findOne/getEntries; assert WRITE on create/addEntry/generateEntries/postEntry against the schedule companyId; move postEntry DRAFT check inside the transaction.' },
  { key: 'financial-statements', ids: ['ITMB-011', 'ITMB-012'], files: ['backend/src/modules/financial-statements/financial-statements.service.ts', 'backend/src/modules/financial-statements/financial-statements.controller.ts', 'backend/src/modules/financial-statements/financial-statements.module.ts'], focus: 'Inject CompanyScopeService; assertCanAccessCompany on findOne(item.companyId) and at the top of generate(companyId, WRITE).' },
  { key: 'fixed-assets', ids: ['ITMB-013'], files: ['backend/src/modules/fixed-assets/fixed-assets.service.ts'], focus: 'On disposal, post the disposal journal entry (remove cost & accumulated depreciation, record proceeds and gain/loss) within a transaction, mirroring depreciation posting. If the posting helper/accounts are unclear, SKIP and report.' },
  { key: 'fuel-credit-sales', ids: ['ITMB-014', 'ITMB-015', 'ITMB-079'], files: ['backend/src/modules/fuel-credit-sales/fuel-credit-sales.service.ts', 'backend/src/modules/fuel-credit-sales/fuel-credit-sales.controller.ts', 'backend/src/modules/fuel-credit-sales/fuel-credit-sales.module.ts'], focus: 'Add CompanyScopeService scoping on findAll/findOne/mutations; wrap credit-sale + receivable creation in one transaction (remove the error-swallowing bare catch); recompute/validate totalAmount = litres*pricePerLitre server-side.' },
  { key: 'fuel-misc', ids: ['ITMB-016', 'ITMB-017', 'ITMB-018'], files: ['backend/src/modules/fuel-daily-reconciliation/fuel-daily-reconciliation.service.ts', 'backend/src/modules/fuel-nozzle-readings/fuel-nozzle-readings.service.ts', 'backend/src/modules/fuel-nozzle-readings/fuel-nozzle-readings.controller.ts', 'backend/src/modules/fuel-nozzle-readings/fuel-nozzle-readings.module.ts', 'backend/src/modules/fuel-tank-dips/fuel-tank-dips.service.ts', 'backend/src/modules/fuel-tank-dips/fuel-tank-dips.controller.ts', 'backend/src/modules/fuel-tank-dips/fuel-tank-dips.module.ts'], focus: 'ITMB-016: scope the reconciliation-number count() to the company (or use the document-number-sequences service) so it is unique per company. ITMB-017/018: add CompanyScopeService scoping on findOne + id mutations (tank-dips list too via companyWhereFor).' },
  { key: 'payroll', ids: ['ITMB-020', 'ITMB-021', 'ITMB-081'], files: ['backend/src/modules/hr/payroll-runs/payroll-runs.service.ts'], focus: 'ITMB-020: floor net pay at 0 (carry-forward or cap deductions; do not persist negative net). ITMB-021: only mark a salary advance recovered/SETTLED when the installment was actually withheld. ITMB-081: de-duplicate LWOP days counted by both approved unpaid leave and UNPAID_ABSENT attendance. Be conservative; SKIP any sub-fix whose correct accrual treatment is unclear.' },
  { key: 'payroll-calc', ids: ['ITMB-059'], files: ['backend/src/modules/hr/payroll-calculator/payroll-calculator.service.ts'], focus: 'Contribute NSSF/PSSSF pension on pensionable earnings only (respect AllowanceType.pensionable) rather than full gross. If the pensionable flag is not readily available in scope, SKIP and report.' },
  { key: 'loans', ids: ['ITMB-063', 'ITMB-105', 'ITMB-026', 'ITMB-062'], files: ['backend/src/modules/loans/loans.service.ts', 'backend/src/modules/loans/dto/create-loan.dto.ts', 'backend/src/modules/loan-repayment-schedules/loan-repayment-schedules.service.ts', 'backend/src/modules/loan-repayment-schedules/loan-repayment-schedules.controller.ts'], focus: 'ITMB-105: add class-validator decorators to create-loan dto (amounts @IsNumber @Min(0), status server-controlled). ITMB-063: derive remaining balance server-side on recordRepayment. ITMB-026: replace @Body() dto:any with a validated DTO, load parent loan and assert company access, derive companyId/loanDebtId from the loan. ITMB-062: guard installment payment with a transaction/atomic update.' },
  { key: 'lease-parking', ids: ['ITMB-025', 'ITMB-027', 'ITMB-028', 'ITMB-065'], files: ['backend/src/modules/lease-agreements/lease-agreements.service.ts', 'backend/src/modules/lease-agreements/lease-agreements.controller.ts', 'backend/src/modules/lease-agreements/dto/create-lease-agreement.dto.ts', 'backend/src/modules/parking-rates/parking-rates.service.ts', 'backend/src/modules/parking-rates/dto/create-parking-rate.dto.ts', 'backend/src/modules/parking-sessions/parking-sessions.service.ts', 'backend/src/modules/parking-sessions/parking-sessions.controller.ts', 'backend/src/modules/parking-sessions/parking-sessions.module.ts'], focus: 'Remove createdById/approvedById from the lease & parking-rate create DTOs; derive createdById from @CurrentUser; keep approval only via the approve endpoint; prevent status=ACTIVE at creation. ITMB-028: add company-scope assert on parking-sessions findOne + mutations (rent-payments/lease/restaurant handled elsewhere). ITMB-065: honour gracePeriodMinutes & maxDailyAmount in parking close().' },
  { key: 'quotations', ids: ['ITMB-032', 'ITMB-033', 'ITMB-034', 'ITMB-035', 'ITMB-071'], files: ['backend/src/modules/quotations/quotations.service.ts'], focus: 'Generate quotation/proforma numbers via the document-number-sequences/entity-code-generator service (or a scoped atomic approach) inside the transaction; wrap quotation->sales-order conversion writes in one transaction; route the SO number through the central sequence (not an ad-hoc timestamp or count+1); ensure converted SO follows the normal create path (inventory/receivable/tax). If the normal SO create path is hard to reuse safely, fix numbering+transaction and SKIP the deeper posting change with a note.' },
  { key: 'rent', ids: ['ITMB-037', 'ITMB-072', 'ITMB-084'], files: ['backend/src/modules/rent-invoices/rent-invoices.service.ts', 'backend/src/modules/rent-invoices/rent-invoices.controller.ts', 'backend/src/modules/rent-invoices/rent-invoices.module.ts'], focus: 'Add CompanyScopeService scoping on findOne + update/issue/remove; do not blind-spread client DTO for scope fields; add a duplicate-period guard so the same lease period cannot be invoiced twice.' },
  { key: 'stock-mut', ids: ['ITMB-042', 'ITMB-043', 'ITMB-029'], files: ['backend/src/modules/stock-adjustments/stock-adjustments.service.ts', 'backend/src/modules/stock-damage/stock-damage.service.ts', 'backend/src/modules/product-batches/product-batches.service.ts'], focus: 'Wrap post() multi-writes in a transaction; guard against re-post double-apply (status check inside tx); add negative-quantity guard on stock-damage; scope product-batch number generation to company (and inside tx). For the document-number count()+1 races, scope the count to the company and generate inside the transaction.' },
  { key: 'inv-bal-mov', ids: ['ITMB-060', 'ITMB-104'], files: ['backend/src/modules/inventory-balances/inventory-balances.service.ts', 'backend/src/modules/inventory-movements/inventory-movements.service.ts'], focus: 'ITMB-060: fix inverted lowStock filter (return rows where quantity>0 AND quantity<=reorder level). ITMB-104: for cost-less inbound movements under WAC, do not value added quantity at existing average (avoid inflating totalValue) — keep totalValue unchanged for zero-cost inbound, or carry prior average correctly.' },
  { key: 'proj-material-harvest', ids: ['ITMB-031', 'ITMB-069', 'ITMB-080', 'ITMB-064'], files: ['backend/src/modules/project-material-issues/project-material-issues.service.ts', 'backend/src/modules/harvest-records/harvest-records.service.ts', 'backend/src/modules/package-movements/package-movements.service.ts'], focus: 'ITMB-031: route post() through the locking balance mutator (no TOCTOU); never record a movement without the matching balance decrement. ITMB-069: flag/guard material issue exceeding BOQ quantity. ITMB-080: use the locking inventory mutator. ITMB-064: handle all movement types and guard against negative owed balance. If the locking mutator API is unclear, at minimum wrap the read-modify-write in a transaction.' },
  { key: 'trips', ids: ['ITMB-044'], files: ['backend/src/modules/trips/trips.service.ts', 'backend/src/modules/trips/trips.controller.ts'], focus: 'Add AuthUser to findOne with assertCanAccessCompany; thread @CurrentUser through findOne and dispatch/markInTransit/complete/close/cancel/remove/getProfitability so each id-based op is company-scoped (WRITE for transitions).' },
  { key: 'ar-ap-po', ids: ['ITMB-036', 'ITMB-070', 'ITMB-078'], files: ['backend/src/modules/receivables/receivables.service.ts', 'backend/src/modules/purchase-orders/purchase-orders.service.ts', 'backend/src/modules/external-payments/external-payments.service.ts'], focus: 'ITMB-036: make receivable payment atomic (mirror payables correct approach / use a transaction + atomic decrement). ITMB-070: PO pay() must add to prior paidAmount (not overwrite), guard within a transaction. ITMB-078: wrap external-payment confirm/reverse status transition in a transaction to close the check-then-act race. (Leave AP/AR settlement JE posting ITMB-045 to another agent.)' },
  { key: 'payables-je', ids: ['ITMB-045'], files: ['backend/src/modules/payables/payables.service.ts'], focus: 'On settlement, post the cash/clearing journal entry so AP control reduces. If the posting helper/accounts are unclear or risky, SKIP with a clear note (do not guess GL accounts).' },
  { key: 'roles-authz', ids: ['ITMB-039', 'ITMB-094', 'ITMB-048'], files: ['backend/src/modules/roles/roles.controller.ts', 'backend/src/modules/roles/roles.service.ts', 'backend/src/common/services/company-scope.service.ts', 'backend/src/common/services/company-scope.service.spec.ts', 'backend/src/common/services/accounting-control.service.ts'], focus: 'ITMB-039: pass @CurrentUser into role create/update; only a GROUP-scoped actor may set scope=GROUP, and the actor must already hold every permission in dto.permissionIds. ITMB-094: do not let GROUP scope unconditionally bypass the AccessLevel check — restrict the blanket bypass to a true super-admin role OR still evaluate the requested minimum; update the two flipped spec cases accordingly. ITMB-048: a period-lock with a date window should only block postings whose date falls in the window, not all postings for the company. These are subtle; SKIP any you cannot make correct.' },
  { key: 'adj-journal-cash-labor-debts', ids: ['ITMB-004', 'ITMB-096', 'ITMB-061', 'ITMB-054', 'ITMB-024', 'ITMB-099'], files: ['backend/src/modules/audit-adjustments/audit-adjustments.service.ts', 'backend/src/modules/journal-entries/journal-entries.service.ts', 'backend/src/modules/cash-accounts/cash-accounts.service.ts', 'backend/src/modules/labor-records/labor-records.service.ts', 'backend/src/modules/debts/debts.service.ts'], focus: 'ITMB-004: enforce exact debits==credits using integer-cents/Decimal compare (remove the 0.01 float tolerance that allows unbalanced posting). ITMB-096: move the period-lock check inside the posting transaction. ITMB-061: validate caller-supplied divisionId/branchId belong to the journal companyId (mirror chart-of-accounts.resolveAccountScope) — validate-only. ITMB-054: do not persist client currentBalance on cash-account create (set 0 / derive). ITMB-024: add company-access assert + validate paymentStatus/totalAmount on labor-records create. ITMB-099: validate debt amountPaid and derive status server-side.' },
  { key: 'construction', ids: ['ITMB-008', 'ITMB-055', 'ITMB-053', 'ITMB-083', 'ITMB-030'], files: ['backend/src/modules/construction-labour-cost/construction-labour-cost.service.ts', 'backend/src/modules/boq-items/boq-items.service.ts', 'backend/src/modules/project-billing/project-billing.service.ts', 'backend/src/modules/proforma-invoices/proforma-invoices.service.ts'], focus: 'ITMB-008: allocate only the project-time portion of gross, not entire gross. ITMB-055: make the reclass credit to 6000 match what was debited. ITMB-053/030: scope BOQ/proforma number count() per parent and generate inside the transaction. ITMB-083: cap project billing billedAmount against contract value/progress. SKIP any accounting sub-fix you cannot make precisely.' },
  { key: 'room-bookings', ids: ['ITMB-040'], files: ['backend/src/modules/room-bookings/room-bookings.service.ts'], focus: 'Reject creating/updating a booking that overlaps an existing active reservation for the same room (date-range overlap check) inside a transaction.' },
  { key: 'infra', ids: ['ITMB-049', 'ITMB-095', 'ITMB-087', 'ITMB-088'], files: ['backend/src/main.ts', 'backend/src/app.module.ts', 'backend/src/common/filters/prisma-exception.filter.ts'], focus: 'ITMB-049: do not hardcode debug logger in production (use debug only when not production). ITMB-095: pass explicit helmet options (HSTS enabled). ITMB-087: optionally tighten/segment throttler (low risk only — keep a sane global). ITMB-088: prisma-exception filter must not return raw driver error text to clients in the default case (return a generic message; log details server-side).' },
  { key: 'injection-ssrf-upload-crypto', ids: ['ITMB-067', 'ITMB-068', 'ITMB-057', 'ITMB-023', 'ITMB-089'], files: ['backend/src/modules/print-engine/print-engine.service.ts', 'backend/src/modules/documents/documents.controller.ts', 'backend/src/modules/integration-connections/integration-connections.service.ts', 'backend/src/common/services/encryption.service.ts'], focus: 'ITMB-067: neutralise leading = + - @ in CSV/Excel cell values. ITMB-068: escape user-controlled strings before building RegExp (or use string replace). ITMB-057: sanitise multer temp filename (strip path separators / use a random name; never use raw originalname). ITMB-023: block SSRF — reject private/loopback/link-local/metadata IPs and disable redirects on the integration test fetch. ITMB-089: make the scrypt salt configurable via env BUT keep the current hardcoded value as the default so EXISTING encrypted data still decrypts (backward compatible) — do NOT change the effective salt.' },
  { key: 'bi-tax-auditlogs', ids: ['ITMB-052', 'ITMB-086', 'ITMB-106', 'ITMB-097'], files: ['backend/src/modules/bi/bi.service.ts', 'backend/src/modules/tax-auto-apply/tax-auto-apply.service.ts', 'backend/src/modules/tax-filing-engine/tax-filing-engine.service.ts', 'backend/src/modules/audit-logs/audit-logs.service.ts'], focus: 'ITMB-052: scope the BI company_comparison/cash_position datasets to accessible companies and bound result size. ITMB-086: tax-auto-apply must not fail open — propagate errors so VAT posting failure does not silently pass (do not block order confirm incorrectly; if behaviour change is risky, at least log+flag). ITMB-106: do not silently fall back to hardcoded CIT/levy rates — surface when no effective rate exists. ITMB-097: bound the getEntityTypes distinct scan (add take / use groupBy with limit).' },
  { key: 'pagination-validation', ids: ['ITMB-007', 'ITMB-066'], files: ['backend/src/modules/chart-of-accounts/dto/query-chart-of-account.dto.ts', 'backend/src/common/dto/pagination-query.dto.ts', 'backend/src/common/dto/pagination.dto.ts', 'backend/src/modules/posting-rules/posting-rules.controller.ts'], focus: 'ITMB-007: add @Max (e.g. 200) to limit and a sane @Max/@Min to page on the chart-of-accounts query DTO and the shared pagination DTO(s) if present. ITMB-066: replace @Body() dto:any in posting-rules.controller with the proper DTO type so the global ValidationPipe runs (use an existing DTO if present; if none exists, SKIP with a note).' },
  { key: 'hr-leave-emp-posting', ids: ['ITMB-101', 'ITMB-102', 'ITMB-058', 'ITMB-082'], files: ['backend/src/modules/hr/leave-requests/leave-requests.service.ts', 'backend/src/modules/hr/employees/employees.service.ts', 'backend/src/modules/posting-runs/posting-runs.service.ts'], focus: 'ITMB-058: scope employee-code count() per company and generate inside a transaction (or use entity-code-generator). ITMB-101: split a year-spanning leave across the correct leave-balance years. ITMB-102: add a cancel path that reverses an approved leave balance. ITMB-082: make posting-runs post/reverse status transition atomic. SKIP leave-accrual changes you cannot make precisely.' },
  { key: 'frontend', ids: ['ITMB-075', 'ITMB-076', 'ITMB-093', 'ITMB-091', 'ITMB-092', 'ITMB-108'], files: ['frontend/src/lib/auth-cookie-config.ts', 'frontend/src/lib/design-system/formatters.ts', 'backend/src/modules/support-tickets/support-tickets.service.ts', 'frontend/src/app/(dashboard)/support/tickets/me/page.tsx', 'frontend/src/app/api/backend/[...path]/route.ts'], focus: 'ITMB-075/076: reduce auth cookie Max-Age to match token lifetimes (access short; refresh/flag ~30d) instead of ~10 years. ITMB-093: formatDateTime must include time (use toLocaleString or explicit hour/minute). ITMB-091: include the user relations in the support-ticket queries so reporter/comment-author names render. ITMB-092: render an error state instead of a permanent Loading spinner when the fetch rejects (wrap in try/catch with error UI). ITMB-108: do not build the proxy origin allowlist from client-controlled Host/X-Forwarded-Host — use a server-configured origin. Keep changes minimal; SKIP ITMB-092 sibling pages you cannot locate.' },
]

const safe = async (p, o) => {
  try { const r = await agent(p, o); return r && Array.isArray(r.reports) ? r : { reports: [] } }
  catch (e) { log('fix agent failed [' + ((o && o.label) || '?') + ']: ' + ((e && e.message) || String(e))); return { reports: [] } }
}

phase('Fix')

const results = await pipeline(
  BATCHES,
  (b) => safe(
    REPO + '\n\nYOUR ASSIGNED FINDINGS: ' + b.ids.join(', ') + '\nFOCUS: ' + b.focus + '\nFILES YOU MAY EDIT (and ONLY these): ' + b.files.join('; ') + SAFETY,
    { label: 'fix:' + b.key, phase: 'Fix', schema: REPORT_SCHEMA }
  ),
  (res, b) => safe(
    REPO + '\n\nRECHECK PASS for batch "' + b.key + '". The previous agent attempted fixes for ' + b.ids.join(', ') + ' in these files: ' + b.files.join('; ') + '. Re-READ each of those files and verify: (1) the code is valid TypeScript (imports present, constructor injection added, controller passes @CurrentUser where a service method now needs AuthUser, no references to undefined symbols), (2) the assigned finding is actually addressed, (3) no unrelated behaviour was changed and no other files were touched. If you find a compile-risk or a missed/incorrect fix WITHIN THESE FILES ONLY, correct it now (minimal, safe). Report final status per id with any file you changed and a note. Do NOT run builds or git.',
    { label: 'recheck:' + b.key, phase: 'Recheck', schema: REPORT_SCHEMA }
  )
)

const reports = results.filter(Boolean).flatMap((r) => (r && r.reports) ? r.reports : [])
const byStatus = {}
for (const r of reports) byStatus[r.status] = (byStatus[r.status] || 0) + 1
return { reports, byStatus, batches: BATCHES.length }
