/** Declarative contract shared by independently owned mutation evidence packs. */

import {
  CrudFixtureAuditAttributionStatus,
  CrudFixtureAuditCompanyBinding,
  CrudFixtureAuditScopeKind,
  CrudFixtureGovernanceContract,
} from './crud-evidence-governance';

export type CrudMutationPrimitive = string | number | boolean | null;

export type CrudMutationValue =
  | { literal: CrudMutationPrimitive }
  | { binding: string; path?: readonly string[] }
  /** Resolves to `${prefix}-${12 lowercase hex characters}`; no implicit truncation. */
  | { unique: { prefix: string } }
  | { now: 'iso' }
  | { array: readonly CrudMutationValue[] }
  | { object: Readonly<Record<string, CrudMutationValue>> };

/** Values available only while verifying an effect after the HTTP response. */
export type CrudMutationEffectValue =
  | CrudMutationValue
  /** Path is evaluated against the standard unwrapped response payload. */
  | { response: { path: readonly string[] } }
  /** References the persisted row (or its id when path is absent) of an earlier named effect. */
  | { effectRef: { effectId: string; path?: readonly string[] } };

/**
 * Closed-world validators for scalar values generated by a create service.
 * These fields are deliberately separate from request-backed expectedFields:
 * a fixture must explain who generated each value and how it is checked.
 */
export type CrudMutationGeneratedField =
  | {
      kind: 'exact';
      value: CrudMutationValue;
    }
  | {
      kind: 'action-time';
      offsetMs?: number;
    }
  | {
      /** Local calendar-day arithmetic (Date.setDate), which is DST-aware. */
      kind: 'action-local-calendar-days';
      offsetDays: number;
    }
  | {
      /** Exact local midnight derived from a signed ISO/date request value. */
      kind: 'local-day-start';
      value: CrudMutationValue;
    }
  | {
      /** Exact final millisecond of the local day derived from a signed ISO/date request value. */
      kind: 'local-day-end';
      value: CrudMutationValue;
    }
  | {
      /** Exact UTC midnight derived from a signed ISO/date request value. */
      kind: 'utc-day-start';
      value: CrudMutationValue;
    }
  | {
      /** Exact final millisecond of the UTC day derived from a signed ISO/date request value. */
      kind: 'utc-day-end';
      value: CrudMutationValue;
    }
  | {
      /**
       * Recomputed from persisted source rows, never from the action response.
       * The loopback verifier owns the independent domain calculation.
       */
      kind: 'independent-domain-aggregate';
      source: 'customer-statement' | 'supplier-statement' | 'financial-trial-balance';
    }
  | {
      /**
       * Proves a one-time response secret against its persisted digest without
       * serializing either value into the signed evidence artifact.
       */
      kind: 'response-secret-digest';
      /** Path within the controller payload, after the global HTTP envelope. */
      responsePath: readonly string[];
      algorithm: 'sha256' | 'hmac-sha256-app-encryption-key';
      encoding: 'hex';
    }
  | {
      /** Proves a non-secret generated scalar against an exact response value. */
      kind: 'response-exact';
      responsePath: readonly string[];
    }
  | {
      /** Proves a persisted secret prefix without writing the response secret to evidence. */
      kind: 'response-secret-prefix';
      responsePath: readonly string[];
      length: number;
    }
  | {
      /** Verifies a one-way password hash against a signed request value in memory only. */
      kind: 'request-secret-hash';
      requestPath: readonly string[];
      algorithm: 'argon2';
    }
  | {
      kind: 'timestamp-id';
      prefix: string;
      timestampEncoding: 'decimal' | 'base36-upper';
      actionLocalCalendarYear?: {
        separator: string;
      };
      randomSuffix?: {
        alphabet: 'base36-upper' | 'hex-upper';
        length: number;
        separator: string;
      };
    }
  | {
      kind: 'value-with-prefix';
      value: CrudMutationValue;
      prefix: string;
      suffix?: string;
    }
  | {
      kind: 'value-with-action-iso-suffix';
      value: CrudMutationValue;
      separator: string;
      suffix?: string;
    }
  | {
      /** Exact idempotency number emitted by TaxAutoApplyService per source line. */
      kind: 'tax-auto-apply-number';
      sourcePrefix: 'SALES' | 'PURCHASE';
      sourceId: CrudMutationValue;
      sourceLineId: CrudMutationValue;
      fragmentLength: 8;
    }
  | {
      /**
       * EntityCodeGeneratorService.next side effect. The loopback runner must
       * prove and recover the exact DocumentNumberSequence delta.
       */
      kind: 'entity-code';
      entityType: string;
      companyId?: CrudMutationValue;
    }
  | {
      /** A deterministic counter derived from the captured pre-action model rows. */
      kind: 'scoped-sequence-id';
      separator: string;
      prefixParts: readonly (
        | { kind: 'literal'; value: string }
        | { kind: 'action-year' }
        | {
            kind: 'company-code';
            companyId: CrudMutationValue;
            preferredField: 'employeeCodePrefix';
            fallbackField: 'code';
            fallbackLength: number;
          }
        | { kind: 'company-id-fragment'; companyId: CrudMutationValue; length: number }
      )[];
      scope: Readonly<Record<string, CrudMutationValue>>;
      counter: {
        strategy: 'count-scope' | 'count-prefix' | 'first-unused-prefix';
        padding: number;
      };
    };

export interface CrudMutationRequestContract {
  path?: Readonly<Record<string, CrudMutationValue>>;
  query?: Readonly<Record<string, CrudMutationValue>>;
  body?: Readonly<Record<string, CrudMutationValue>>;
}

export interface CrudMutationTarget {
  model: string;
  id: CrudMutationValue;
}

export interface CrudMutationPreState extends CrudMutationTarget {
  /** Applied before the fixture's before-snapshot; never counted as the tested effect. */
  fields: Readonly<Record<string, CrudMutationValue>>;
}

/**
 * Deliberately closed selector for a recovery scope. Operators, raw Prisma
 * filters, relation traversal and free-form query fragments are not admitted.
 */
export interface CrudMutationClosedScope {
  equals: Readonly<Record<string, CrudMutationValue>>;
  /** Exact scalar identity tuple used to bind and restore the pre-action set. */
  identityFields: readonly string[];
}

interface CrudMutationCompoundEffectBase {
  effectId: string;
  model: string;
  /** Lower values recover first; every effect/exception order must be unique. */
  recoveryOrder: number;
}

export type CrudMutationCompoundNamedEffect =
  | (CrudMutationCompoundEffectBase & {
      kind: 'row-create';
      id: CrudMutationEffectValue;
      expectedFields: Readonly<Record<string, CrudMutationEffectValue>>;
      recovery: 'delete-created';
    })
  | (CrudMutationCompoundEffectBase & {
      /**
       * A service-created row whose identity is not available until after the
       * action. The runner takes an exact pre-action scope snapshot, requires
       * one (and only one) new identity in that scope, and closes every scalar
       * on the discovered row using the same field contract as a singular
       * create.
       */
      kind: 'scoped-row-create';
      scope: CrudMutationClosedScope;
      /** Every business scalar that the discovered row must persist. */
      expectedFields: Readonly<Record<string, CrudMutationEffectValue>>;
      /** Every service-generated scalar, with a semantic validator. */
      generatedFields: Readonly<Record<string, CrudMutationGeneratedField>>;
      /** Prisma-managed identity/timestamp fields, validated from schema semantics. */
      allowedFields?: readonly string[];
      recovery: 'restore-scope';
    })
  | (CrudMutationCompoundEffectBase & {
      kind: 'row-update';
      id: CrudMutationValue;
      expectedFields: Readonly<Record<string, CrudMutationEffectValue>>;
      forbiddenFields?: readonly string[];
      recovery: 'restore-row';
    })
  | (CrudMutationCompoundEffectBase & {
      kind: 'row-delete';
      id: CrudMutationValue;
      mode: 'soft' | 'hard';
      deletedAtPath?: readonly string[];
      /** Every scalar field changed by a soft delete must be declared here. */
      expectedFields: Readonly<Record<string, CrudMutationEffectValue>>;
      recovery: 'restore-row';
    })
  | (CrudMutationCompoundEffectBase & {
      kind: 'count-delta';
      scope: CrudMutationClosedScope;
      expectedDelta: number;
      recovery: 'restore-scope';
    })
  | (CrudMutationCompoundEffectBase & {
      kind: 'set-delta';
      scope: CrudMutationClosedScope;
      expectedAdded: readonly Readonly<Record<string, CrudMutationEffectValue>>[];
      expectedRemoved: readonly Readonly<Record<string, CrudMutationEffectValue>>[];
      recovery: 'restore-scope';
    });

export type CrudMutationAllowedTableExceptionReason =
  | 'database_trigger'
  | 'denormalized_projection'
  | 'framework_bookkeeping';

export interface CrudMutationAllowedTableException {
  reason: CrudMutationAllowedTableExceptionReason;
  detail: string;
  /** A complete, asserted database delta contract; prose alone grants no table authority. */
  effect: CrudMutationCompoundNamedEffect;
}

export interface CrudMutationCompoundEffect {
  kind: 'compound';
  effects: readonly CrudMutationCompoundNamedEffect[];
  /**
   * Database-only exceptions. File, email, messaging, network and other
   * external effects intentionally have no representable recovery contract.
   */
  allowedTableExceptions?: readonly CrudMutationAllowedTableException[];
  /** Exact entity id expected on the one attributable audit row. */
  auditEntityId: CrudMutationEffectValue;
}

export type CrudMutationSingularEffect =
  | {
      kind: 'create';
      model: string;
      /** Evaluated against the standard unwrapped response payload (`data` when present). */
      responseIdPath: readonly string[];
      companyPath?: readonly string[];
      /** Every business scalar that the create must persist. */
      expectedFields: Readonly<Record<string, CrudMutationValue>>;
      /** Every service-generated scalar, with a semantic validator. */
      generatedFields: Readonly<Record<string, CrudMutationGeneratedField>>;
      /** Prisma-managed identity/timestamp fields; the harness validates their schema semantics. */
      allowedFields?: readonly string[];
    }
  | {
      kind: 'update';
      model: string;
      id: CrudMutationValue;
      expectedFields: Readonly<Record<string, CrudMutationValue>>;
      /** Optional framework-managed scalar deltas that may occur in addition to expectedFields. */
      allowedFields?: readonly string[];
    }
  | {
      kind: 'delete';
      model: string;
      id: CrudMutationValue;
      mode: 'soft' | 'hard';
      deletedAtPath?: readonly string[];
      /** Every scalar delta caused by deletion (including deletedAt for soft deletes). */
      expectedFields: Readonly<Record<string, CrudMutationValue>>;
      allowedFields?: readonly string[];
    }
  | {
      kind: 'transition';
      model: string;
      id: CrudMutationValue;
      expectedFields: Readonly<Record<string, CrudMutationValue>>;
      forbiddenFields?: readonly string[];
      /** Optional framework-managed scalar deltas that may occur in addition to expectedFields. */
      allowedFields?: readonly string[];
    }
  | {
      /**
       * An update whose new scalars are generated at execution time rather than
       * copied from the signed request (for example an expiring one-time-secret
       * digest). The validators are identical to create validators so raw
       * secrets never enter the evidence artifact.
       */
      kind: 'generated-transition';
      model: string;
      id: CrudMutationValue;
      expectedFields: Readonly<Record<string, CrudMutationValue>>;
      generatedFields: Readonly<Record<string, CrudMutationGeneratedField>>;
      forbiddenFields?: readonly string[];
      /** Optional framework-managed scalar deltas, limited by the runner. */
      allowedFields?: readonly string[];
    }
  | {
      /**
       * A command whose sole persistent effect is its attributable append-only
       * audit record. This is intentionally distinct from a no-op transition:
       * the database sentinel still proves that no business model changed.
       */
      kind: 'audit-only';
      /** Existing row that anchors the command's signed company/resource scope. */
      model: string;
      id: CrudMutationValue;
      /** Must remain empty: declaring a business-field delta would contradict this effect kind. */
      expectedFields: Readonly<Record<string, never>>;
      auditEntityId: CrudMutationValue;
    };

export type CrudMutationEffect = CrudMutationSingularEffect | CrudMutationCompoundEffect;

export type CrudMutationAuditCompanyContract =
  | {
      /** Bind AuditLog.companyId to the company scalar declared by the persisted effect. */
      kind: 'effect-company';
    }
  | {
      /** Explicitly bind a global or exceptional audit company to a signed fixture value. */
      kind: 'exact';
      value: CrudMutationValue;
    };

export interface CrudMutationAuditPayloadContract {
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  oldValue?: CrudMutationValue;
  newValue?: CrudMutationValue;
  metadata?: CrudMutationValue;
  /** Controller-payload paths whose values must not occur anywhere in stored audit JSON. */
  responseSecretsAbsent?: readonly (readonly string[])[];
  /** Sensitive key names that must not occur anywhere in stored audit JSON. */
  forbiddenKeys?: readonly string[];
}

/**
 * An additional attributable audit row intentionally emitted by one HTTP
 * action. The entity may be a dynamic compound effect (for example the stock
 * movement created while posting damage), but its company/scope provenance is
 * still an exact signed contract.
 */
export interface CrudMutationAdditionalAuditContract {
  entityType: string;
  action: string;
  entityId: CrudMutationEffectValue;
  companyId: CrudMutationAuditCompanyContract;
  scopeKind: Extract<CrudFixtureAuditScopeKind, 'COMPANY' | 'MULTI_COMPANY' | 'GLOBAL'>;
  companyScopeBindings?: readonly CrudFixtureAuditCompanyBinding[];
  attributionStatus: Extract<CrudFixtureAuditAttributionStatus, 'EXPLICIT' | 'RESOLVED'>;
  payload?: CrudMutationAuditPayloadContract;
}

export interface CrudMutationAuditContract {
  required: true;
  entityType: string;
  action: string;
  /** Override the default effect-row id when the service audits a parent aggregate. */
  entityId?: CrudMutationValue;
  companyId: CrudMutationAuditCompanyContract;
  /** Immutable scope classification paired with the signed company snapshot source. */
  scopeKind?: Extract<CrudFixtureAuditScopeKind, 'COMPANY' | 'MULTI_COMPANY' | 'GLOBAL'>;
  /** Exact company snapshots for a multi-company audit with a null compatibility company. */
  companyScopeBindings?: readonly CrudFixtureAuditCompanyBinding[];
  /**
   * Exact provenance of the immutable scope snapshot. EXPLICIT means the
   * application policy path supplied it; RESOLVED means the audit boundary
   * recovered it from trusted persisted state. These are intentionally not
   * interchangeable in signed evidence.
   */
  attributionStatus?: Extract<CrudFixtureAuditAttributionStatus, 'EXPLICIT' | 'RESOLVED'>;
  /** Optional exact payload/severity and DLP proof for security-sensitive actions. */
  payload?: CrudMutationAuditPayloadContract;
  /** Every non-primary attributable audit row; undeclared rows still fail closed. */
  additionalAudits?: readonly CrudMutationAdditionalAuditContract[];
}

export function crudMutationAuditScopeKind(
  company: CrudMutationAuditCompanyContract,
): Extract<CrudFixtureAuditScopeKind, 'COMPANY' | 'GLOBAL'> {
  return company.kind === 'exact' && 'literal' in company.value && company.value.literal === null
    ? 'GLOBAL'
    : 'COMPANY';
}

export interface CrudMutationFixtureRegistration<
  TEffect extends CrudMutationEffect = CrudMutationSingularEffect,
> {
  fixtureId: string;
  fixtureVersion: 1;
  capabilityId: string;
  controlKind: 'positive';
  description: string;
  governance: CrudFixtureGovernanceContract;
  packId: string;
  operation: 'create' | 'update' | 'delete' | 'action';
  setupModels?: readonly string[];
  request: CrudMutationRequestContract;
  target?: CrudMutationTarget;
  /** Exact prerequisite state reset for this fixture in the shared disposable schema. */
  preState?: CrudMutationPreState;
  /**
   * Additional exact prerequisite rows. This is additive to `preState` so
   * existing single-target fixtures retain their signed contract shape while
   * actions that depend on related rows can declare and recover them too.
   */
  preStates?: readonly CrudMutationPreState[];
  effect: TEffect;
  audit: CrudMutationAuditContract;
  executionPrincipal?: 'company' | 'group' | 'poster';
  /** Disposable-runner-only rollout flags, restored immediately after invocation. */
  testEnvironment?: Readonly<{ TAX_AUTO_APPLY?: 'true' }>;
}

export type CrudMutationAnyFixtureRegistration =
  CrudMutationFixtureRegistration<CrudMutationEffect>;

export interface CrudMutationFixturePack<
  TEffect extends CrudMutationEffect = CrudMutationSingularEffect,
> {
  packId: string;
  packVersion: 1;
  fixtures: readonly CrudMutationFixtureRegistration<TEffect>[];
}

export type CrudMutationAnyFixturePack = CrudMutationFixturePack<CrudMutationEffect>;

export interface CrudMutationBlocker {
  capabilityId: string;
  reason:
    | 'body_schema_not_strict'
    | 'required_transport_not_represented'
    | 'isolated_seed_not_available'
    | 'exact_effect_not_represented'
    | 'audit_attribution_not_persisted'
    | 'irreversible_without_recovery_control';
  detail: string;
}

export interface CrudMutationRecoveryPlanItem {
  source: 'effect' | 'allowed-table-exception' | 'generated-field';
  contractId: string;
  model: string;
  recovery: 'restore-row' | 'delete-created' | 'restore-scope';
  recoveryOrder: number;
}

export interface CrudMutationResolvedModelDelta {
  model: string;
  created: readonly string[];
  deleted: readonly string[];
  updated: readonly { identity: string; fields: readonly string[] }[];
}

export type CrudMutationResolvedDeltaClaim =
  | { claimId: string; model: string; kind: 'create' | 'delete'; identity: string }
  | {
      claimId: string;
      model: string;
      kind: 'update';
      identity: string;
      fields: readonly string[];
    };

export interface CrudMutationScopedRowCreateIdentityDelta {
  added: readonly string[];
  removed: readonly string[];
  duplicateBefore: readonly string[];
  duplicateAfter: readonly string[];
  isExactCreate: boolean;
}

/**
 * Pure closed-scope identity comparison shared by the loopback runner and its
 * focused contract tests. Duplicate declared identities fail closed even when
 * set arithmetic would otherwise look like one create.
 */
export function resolveCrudMutationScopedRowCreateIdentityDelta(
  before: readonly string[],
  after: readonly string[],
): CrudMutationScopedRowCreateIdentityDelta {
  const duplicates = (values: readonly string[]) =>
    [...new Set(values.filter((value, index) => values.indexOf(value) !== index))].sort();
  const duplicateBefore = duplicates(before);
  const duplicateAfter = duplicates(after);
  const beforeSet = new Set(before);
  const afterSet = new Set(after);
  const added = [...afterSet].filter((identity) => !beforeSet.has(identity)).sort();
  const removed = [...beforeSet].filter((identity) => !afterSet.has(identity)).sort();
  return Object.freeze({
    added: Object.freeze(added),
    removed: Object.freeze(removed),
    duplicateBefore: Object.freeze(duplicateBefore),
    duplicateAfter: Object.freeze(duplicateAfter),
    isExactCreate:
      duplicateBefore.length === 0 &&
      duplicateAfter.length === 0 &&
      added.length === 1 &&
      removed.length === 0,
  });
}

/**
 * Exhaustively reconciles every model/identity/field delta. Missing, duplicate,
 * overlapping, or assertion-only claims all fail; recovery is not evidence.
 */
export function reconcileCrudMutationModelDeltas(
  deltas: readonly CrudMutationResolvedModelDelta[],
  claims: readonly CrudMutationResolvedDeltaClaim[],
): readonly string[] {
  const actual = new Set<string>();
  const claimed = new Map<string, string[]>();
  const key = (model: string, kind: string, identity: string, field?: string) =>
    [model, kind, identity, field ?? ''].join('\u001f');

  for (const delta of deltas) {
    for (const identity of delta.created) actual.add(key(delta.model, 'create', identity));
    for (const identity of delta.deleted) actual.add(key(delta.model, 'delete', identity));
    for (const update of delta.updated) {
      for (const field of update.fields)
        actual.add(key(delta.model, 'update', update.identity, field));
    }
  }
  for (const claim of claims) {
    const keys =
      claim.kind === 'update'
        ? claim.fields.map((field) => key(claim.model, claim.kind, claim.identity, field))
        : [key(claim.model, claim.kind, claim.identity)];
    for (const claimKey of keys) {
      const owners = claimed.get(claimKey) ?? [];
      owners.push(claim.claimId);
      claimed.set(claimKey, owners);
    }
  }

  const errors: string[] = [];
  for (const actualKey of [...actual].sort()) {
    const owners = claimed.get(actualKey) ?? [];
    if (owners.length === 0) errors.push(`undeclared delta ${displayDeltaKey(actualKey)}`);
    else if (owners.length > 1) {
      errors.push(`overlapping delta ${displayDeltaKey(actualKey)} claimed by ${owners.join(',')}`);
    }
  }
  for (const [claimKey, owners] of [...claimed].sort(([left], [right]) =>
    left.localeCompare(right),
  )) {
    if (!actual.has(claimKey)) {
      errors.push(`claimed delta absent ${displayDeltaKey(claimKey)} by ${owners.join(',')}`);
    }
  }
  return Object.freeze(errors);
}

function displayDeltaKey(value: string): string {
  const [model, kind, identity, field] = value.split('\u001f');
  return `${model}.${kind}[${identity}]${field ? `.${field}` : ''}`;
}

/** Default-deny model set. The audit parent and immutable scope child are one ledger effect. */
export function crudMutationAllowedModels(effect: CrudMutationEffect): ReadonlySet<string> {
  if (effect.kind === 'audit-only') {
    return new Set(['AuditLog', 'AuditLogCompanyScope']);
  }
  if (effect.kind !== 'compound') {
    const models = new Set([effect.model, 'AuditLog', 'AuditLogCompanyScope']);
    if (
      effect.kind === 'create' &&
      Object.values(effect.generatedFields).some((field) => field.kind === 'entity-code')
    ) {
      models.add('DocumentNumberSequence');
    }
    return models;
  }
  return new Set([
    ...effect.effects.map((item) => item.model),
    ...(effect.allowedTableExceptions ?? []).map((item) => item.effect.model),
    'AuditLog',
    'AuditLogCompanyScope',
  ]);
}

/**
 * Models reconciled by the mutation's business-effect contract. AuditLog and
 * its immutable company-scope children remain allowed by the table policy, but
 * are reconciled together by the fixture's exact audit contract instead of
 * being misclassified as undeclared compound business effects.
 */
export function crudMutationBusinessDeltaModels(effect: CrudMutationEffect): ReadonlySet<string> {
  return new Set(
    [...crudMutationAllowedModels(effect)].filter(
      (model) => model !== 'AuditLog' && model !== 'AuditLogCompanyScope',
    ),
  );
}

export function crudMutationUnexpectedModels(
  effect: CrudMutationEffect,
  changedModels: readonly string[],
): readonly string[] {
  const allowed = crudMutationAllowedModels(effect);
  return Object.freeze([...new Set(changedModels)].sort().filter((model) => !allowed.has(model)));
}

export function crudMutationRecoveryPlan(
  effect: CrudMutationEffect,
): readonly CrudMutationRecoveryPlanItem[] {
  if (effect.kind === 'audit-only') return Object.freeze([]);
  if (effect.kind !== 'compound') {
    return Object.freeze([
      {
        source: 'effect' as const,
        contractId: 'primary',
        model: effect.model,
        recovery: effect.kind === 'create' ? 'delete-created' : 'restore-row',
        recoveryOrder: 0,
      },
      ...(effect.kind === 'create'
        ? Object.entries(effect.generatedFields)
            .filter(([, field]) => field.kind === 'entity-code')
            .map(([field], index) => ({
              source: 'generated-field' as const,
              contractId: `generated:${field}`,
              model: 'DocumentNumberSequence',
              recovery: 'restore-scope' as const,
              recoveryOrder: index + 1,
            }))
        : []),
    ]);
  }
  return Object.freeze(
    [
      ...effect.effects.map((item) => ({
        source: 'effect' as const,
        contractId: item.effectId,
        model: item.model,
        recovery: item.recovery,
        recoveryOrder: item.recoveryOrder,
      })),
      ...(effect.allowedTableExceptions ?? []).map((item) => ({
        source: 'allowed-table-exception' as const,
        contractId: item.effect.effectId,
        model: item.effect.model,
        recovery: item.effect.recovery,
        recoveryOrder: item.effect.recoveryOrder,
      })),
    ].sort(
      (left, right) =>
        left.recoveryOrder - right.recoveryOrder || left.contractId.localeCompare(right.contractId),
    ),
  );
}

/**
 * Source-only validation used by manifest packs and focused tests. Live DMMF
 * validation of model/field existence remains the disposable runner's job.
 */
export function validateCrudMutationFixtureContract(
  fixture: CrudMutationAnyFixtureRegistration,
): readonly string[] {
  const errors: string[] = [];
  if (fixture.preStates && fixture.preStates.length === 0) {
    errors.push('preStates must not be empty when declared');
  }
  if (
    fixture.testEnvironment?.TAX_AUTO_APPLY !== undefined &&
    !fixture.capabilityId.startsWith('TaxAutoApplyController.')
  ) {
    errors.push('TAX_AUTO_APPLY test environment is restricted to TaxAutoApplyController');
  }
  const prerequisiteStates = [
    ...(fixture.preState ? [fixture.preState] : []),
    ...(fixture.preStates ?? []),
  ];
  for (const [index, preState] of prerequisiteStates.entries()) {
    if (Object.keys(preState.fields).length === 0) {
      errors.push(`preState ${index} fields must not be empty`);
    }
  }
  if (fixture.governance.scope !== 'not_applicable' || fixture.governance.audit !== 'required') {
    errors.push('mutation governance must require audit with scope not_applicable');
  }
  if (
    !fixture.audit.companyId ||
    !['effect-company', 'exact'].includes(fixture.audit.companyId.kind)
  ) {
    errors.push('audit.companyId must carry an exact signed binding contract');
  } else if (!fixture.audit.scopeKind) {
    errors.push('audit.scopeKind must declare the immutable audit scope classification');
  } else {
    const companyScopeBindings = fixture.audit.companyScopeBindings ?? [];
    const uniqueCompanyScopeBindings = new Set(companyScopeBindings);
    if (uniqueCompanyScopeBindings.size !== companyScopeBindings.length) {
      errors.push('audit.companyScopeBindings must not contain duplicate company snapshots');
    }
    if (fixture.audit.scopeKind === 'MULTI_COMPANY') {
      const compatibilityCompanyIsGlobal =
        fixture.audit.companyId.kind === 'exact' &&
        'literal' in fixture.audit.companyId.value &&
        fixture.audit.companyId.value.literal === null;
      if (!compatibilityCompanyIsGlobal) {
        errors.push('MULTI_COMPANY audit.companyId must be the exact null compatibility value');
      }
      if (uniqueCompanyScopeBindings.size < 2) {
        errors.push('MULTI_COMPANY audit must bind at least two exact company snapshots');
      }
    } else {
      if (companyScopeBindings.length > 0) {
        errors.push(`${fixture.audit.scopeKind} audit cannot declare multi-company snapshots`);
      }
      if (fixture.audit.scopeKind !== crudMutationAuditScopeKind(fixture.audit.companyId)) {
        errors.push('audit.scopeKind must match the signed audit company snapshot contract');
      }
    }
  }
  if (!['EXPLICIT', 'RESOLVED'].includes(fixture.audit.attributionStatus ?? '')) {
    errors.push('audit.attributionStatus must declare exact EXPLICIT or RESOLVED provenance');
  }
  for (const [index, path] of (fixture.audit.payload?.responseSecretsAbsent ?? []).entries()) {
    if (
      path.length === 0 ||
      path.length > 8 ||
      path.some((segment) => !/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(segment))
    ) {
      errors.push(`audit.payload.responseSecretsAbsent[${index}] has an invalid response path`);
    }
  }
  for (const key of fixture.audit.payload?.forbiddenKeys ?? []) {
    if (!/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(key)) {
      errors.push(`audit.payload forbidden key ${key} is invalid`);
    }
  }
  if (fixture.audit.additionalAudits && fixture.audit.additionalAudits.length === 0) {
    errors.push('audit.additionalAudits must not be empty when declared');
  }
  const additionalAuditSignatures = new Set<string>();
  for (const [index, audit] of (fixture.audit.additionalAudits ?? []).entries()) {
    const label = `audit.additionalAudits[${index}]`;
    const signature = `${audit.action}\u001f${audit.entityType}`;
    if (additionalAuditSignatures.has(signature)) {
      errors.push(`${label} duplicates an action/entityType audit contract`);
    }
    additionalAuditSignatures.add(signature);
    if (!audit.action.trim() || !audit.entityType.trim()) {
      errors.push(`${label} action and entityType must not be empty`);
    }
    const companyScopeBindings = audit.companyScopeBindings ?? [];
    const uniqueCompanyScopeBindings = new Set(companyScopeBindings);
    if (uniqueCompanyScopeBindings.size !== companyScopeBindings.length) {
      errors.push(`${label}.companyScopeBindings contains duplicate company snapshots`);
    }
    if (audit.scopeKind === 'MULTI_COMPANY') {
      const compatibilityCompanyIsGlobal =
        audit.companyId.kind === 'exact' &&
        'literal' in audit.companyId.value &&
        audit.companyId.value.literal === null;
      if (!compatibilityCompanyIsGlobal || uniqueCompanyScopeBindings.size < 2) {
        errors.push(
          `${label} MULTI_COMPANY scope requires null compatibility company and two snapshots`,
        );
      }
    } else if (
      companyScopeBindings.length > 0 ||
      audit.scopeKind !== crudMutationAuditScopeKind(audit.companyId)
    ) {
      errors.push(`${label} scope does not match its signed company contract`);
    }
    if (!['EXPLICIT', 'RESOLVED'].includes(audit.attributionStatus)) {
      errors.push(`${label}.attributionStatus must be EXPLICIT or RESOLVED`);
    }
    if ('response' in audit.entityId && audit.entityId.response.path.length === 0) {
      errors.push(`${label}.entityId response path must not be empty`);
    }
  }
  if (fixture.effect.kind !== 'compound') {
    for (const [index, audit] of (fixture.audit.additionalAudits ?? []).entries()) {
      if ('effectRef' in audit.entityId) {
        errors.push(
          `audit.additionalAudits[${index}].entityId cannot reference an effect on a singular fixture`,
        );
      }
    }
    if (fixture.effect.kind === 'audit-only') {
      const value = fixture.effect.auditEntityId;
      if (Object.keys(fixture.effect.expectedFields).length > 0) {
        errors.push('audit-only expectedFields must be empty');
      }
      if ('now' in value || 'array' in value || 'object' in value) {
        errors.push('audit-only auditEntityId must be a stable scalar value');
      }
      return Object.freeze(errors);
    }
    if (
      fixture.effect.kind === 'create' ||
      fixture.effect.kind === 'update' ||
      fixture.effect.kind === 'delete' ||
      fixture.effect.kind === 'transition' ||
      fixture.effect.kind === 'generated-transition'
    ) {
      validateMutationFieldDeclarations(
        errors,
        fixture.effect.expectedFields,
        fixture.effect.kind === 'create' || fixture.effect.kind === 'generated-transition'
          ? fixture.effect.generatedFields
          : {},
        fixture.effect.allowedFields ?? [],
      );
      if (fixture.effect.kind === 'transition' || fixture.effect.kind === 'generated-transition') {
        for (const field of fixture.effect.allowedFields ?? []) {
          if (fixture.effect.forbiddenFields?.includes(field)) {
            errors.push(`allowed field ${field} is also forbidden`);
          }
        }
      }
    }
    return Object.freeze(errors);
  }
  const compoundEffect = fixture.effect;
  const effectIds = new Set<string>();
  const referenceableEffectIds = new Set<string>();
  const recoveryOrders = new Set<number>();

  // A named-effect envelope also covers commands whose sole business delta is
  // one dynamically identified row (for example TaxAutoApply). Closed-table
  // reconciliation, scalar closure and exact recovery remain identical.
  if (fixture.effect.effects.length === 0) {
    errors.push('compound effects require at least one named effect');
  }

  const validateOrder = (order: number, label: string) => {
    if (!Number.isSafeInteger(order) || order < 0) {
      errors.push(`${label} recoveryOrder must be a non-negative safe integer`);
    } else if (recoveryOrders.has(order)) {
      errors.push(`${label} recoveryOrder ${order} is duplicated`);
    }
    recoveryOrders.add(order);
  };
  const validateScope = (scope: CrudMutationClosedScope, label: string) => {
    const fields = Object.keys(scope.equals);
    if (fields.length === 0) errors.push(`${label} scope.equals must not be empty`);
    if (scope.identityFields.length === 0) errors.push(`${label} identityFields must not be empty`);
    if (new Set(scope.identityFields).size !== scope.identityFields.length) {
      errors.push(`${label} identityFields must be unique`);
    }
    for (const field of [...fields, ...scope.identityFields]) {
      if (!/^[A-Za-z][A-Za-z0-9_]{0,127}$/.test(field)) {
        errors.push(`${label} contains an unsafe field name ${field}`);
      }
    }
    for (const [field, value] of Object.entries(scope.equals)) {
      if ('now' in value || 'array' in value || 'object' in value) {
        errors.push(`${label} scope field ${field} is not a stable scalar equality value`);
      }
    }
  };
  const validateEffectValue = (
    value: CrudMutationEffectValue,
    label: string,
    availableEffectIds: ReadonlySet<string>,
  ) => {
    if ('response' in value && value.response.path.length === 0) {
      errors.push(`${label} response path must not be empty`);
    }
    if ('effectRef' in value && !availableEffectIds.has(value.effectRef.effectId)) {
      errors.push(`${label} references unavailable prior effect ${value.effectRef.effectId}`);
    }
  };

  const validateNamedEffect = (effect: CrudMutationCompoundNamedEffect, label: string) => {
    const priorEffectIds = new Set(referenceableEffectIds);
    if (!/^[A-Za-z][A-Za-z0-9_-]{0,63}$/.test(effect.effectId)) {
      errors.push(`effectId ${effect.effectId} is invalid`);
    }
    if (effectIds.has(effect.effectId)) errors.push(`effectId ${effect.effectId} is duplicated`);
    validateOrder(effect.recoveryOrder, label);
    if (!effect.model.trim()) errors.push(`${label} model must not be empty`);

    if (effect.kind === 'row-create') {
      validateEffectValue(effect.id, `${effect.effectId}.id`, priorEffectIds);
      if (Object.keys(effect.expectedFields).length === 0) {
        errors.push(`${effect.effectId}.expectedFields must not be empty`);
      }
      for (const [field, value] of Object.entries(effect.expectedFields)) {
        validateEffectValue(value, `${effect.effectId}.expectedFields.${field}`, priorEffectIds);
      }
    } else if (effect.kind === 'scoped-row-create') {
      validateScope(effect.scope, `effect ${effect.effectId}`);
      validateMutationFieldDeclarations(
        errors,
        effect.expectedFields,
        effect.generatedFields,
        effect.allowedFields ?? [],
        effect.effectId,
      );
      for (const [field, value] of Object.entries(effect.expectedFields)) {
        validateEffectValue(value, `${effect.effectId}.expectedFields.${field}`, priorEffectIds);
      }
      for (const [field, validator] of Object.entries(effect.generatedFields)) {
        const sequenceModeled = [
          ...compoundEffect.effects,
          ...(compoundEffect.allowedTableExceptions ?? []).map((exception) => exception.effect),
        ].some((candidate) => candidate.model === 'DocumentNumberSequence');
        if (validator.kind === 'entity-code' && !sequenceModeled) {
          errors.push(
            `${effect.effectId}.generated field ${field} must declare its sequence as a separate compound effect`,
          );
        }
      }
    } else if (effect.kind === 'row-update' || effect.kind === 'row-delete') {
      if (Object.keys(effect.expectedFields).length === 0) {
        errors.push(`${effect.effectId}.expectedFields must not be empty`);
      }
      for (const [field, value] of Object.entries(effect.expectedFields)) {
        validateEffectValue(value, `${effect.effectId}.expectedFields.${field}`, priorEffectIds);
      }
    } else if (effect.kind === 'count-delta') {
      validateScope(effect.scope, `effect ${effect.effectId}`);
      if (!Number.isSafeInteger(effect.expectedDelta) || effect.expectedDelta === 0) {
        errors.push(`${effect.effectId}.expectedDelta must be a non-zero safe integer`);
      }
    } else if (effect.kind === 'set-delta') {
      validateScope(effect.scope, `effect ${effect.effectId}`);
      if (effect.expectedAdded.length === 0 && effect.expectedRemoved.length === 0) {
        errors.push(`${effect.effectId} must declare an added or removed identity`);
      }
      for (const [setName, identities] of [
        ['expectedAdded', effect.expectedAdded],
        ['expectedRemoved', effect.expectedRemoved],
      ] as const) {
        for (const [index, identity] of identities.entries()) {
          if (!sameFieldSet(Object.keys(identity), effect.scope.identityFields)) {
            errors.push(
              `${effect.effectId}.${setName}[${index}] must contain exactly the identityFields`,
            );
          }
          for (const [field, value] of Object.entries(identity)) {
            validateEffectValue(
              value,
              `${effect.effectId}.${setName}[${index}].${field}`,
              priorEffectIds,
            );
          }
        }
      }
    }
    effectIds.add(effect.effectId);
    if (
      effect.kind === 'row-create' ||
      effect.kind === 'scoped-row-create' ||
      effect.kind === 'row-update' ||
      effect.kind === 'row-delete'
    ) {
      referenceableEffectIds.add(effect.effectId);
    }
  };

  for (const effect of fixture.effect.effects) {
    validateNamedEffect(effect, `effect ${effect.effectId}`);
  }

  const effectModels = new Set(fixture.effect.effects.map((effect) => effect.model));
  for (const [index, exception] of (fixture.effect.allowedTableExceptions ?? []).entries()) {
    const label = `allowedTableExceptions[${index}]`;
    if (exception.detail.trim().length < 8 || exception.detail.length > 256) {
      errors.push(`${label}.detail must contain 8-256 characters`);
    }
    if (
      !['database_trigger', 'denormalized_projection', 'framework_bookkeeping'].includes(
        exception.reason,
      )
    ) {
      errors.push(`${label}.reason is not an allowed database-only exception reason`);
    }
    if (effectModels.has(exception.effect.model)) {
      errors.push(`${label}.model is already declared by a semantic effect`);
    }
    validateNamedEffect(exception.effect, `${label}.effect`);
  }

  const allNamedEffects = [
    ...fixture.effect.effects,
    ...(fixture.effect.allowedTableExceptions ?? []).map((exception) => exception.effect),
  ];
  for (const deleted of allNamedEffects) {
    if (deleted.kind !== 'row-delete' || deleted.recovery !== 'restore-row') continue;
    for (const replacement of allNamedEffects) {
      if (
        replacement.kind !== 'scoped-row-create' ||
        replacement.recovery !== 'restore-scope' ||
        replacement.model !== deleted.model
      ) {
        continue;
      }
      if (replacement.recoveryOrder >= deleted.recoveryOrder) {
        errors.push(
          `${replacement.effectId} restore-scope recoveryOrder ${replacement.recoveryOrder} must precede ${deleted.effectId} restore-row recoveryOrder ${deleted.recoveryOrder} for model ${deleted.model}`,
        );
      }
    }
  }
  validateEffectValue(fixture.effect.auditEntityId, 'auditEntityId', referenceableEffectIds);
  for (const [index, audit] of (fixture.audit.additionalAudits ?? []).entries()) {
    validateEffectValue(
      audit.entityId,
      `audit.additionalAudits[${index}].entityId`,
      referenceableEffectIds,
    );
  }
  return Object.freeze(errors);
}

function sameFieldSet(left: readonly string[], right: readonly string[]): boolean {
  return (
    left.length === right.length &&
    [...left].sort().every((value, index) => value === [...right].sort()[index])
  );
}

const SAFE_MUTATION_FIELD_NAME = /^[A-Za-z][A-Za-z0-9_]{0,127}$/;

function validateMutationFieldDeclarations(
  errors: string[],
  expectedFields: Readonly<Record<string, unknown>>,
  generatedFields: Readonly<Record<string, CrudMutationGeneratedField>>,
  allowedFields: readonly string[],
  label = '',
): void {
  const prefix = label ? `${label}.` : '';
  const expected = Object.keys(expectedFields);
  const generated = Object.keys(generatedFields);
  if (expected.length === 0 && generated.length === 0) {
    errors.push(`${prefix}expectedFields/generatedFields must not both be empty`);
  }
  if (new Set(generated).size !== generated.length) {
    errors.push(`${prefix}generatedFields must be unique`);
  }
  if (new Set(allowedFields).size !== allowedFields.length) {
    errors.push(`${prefix}allowedFields must be unique`);
  }
  for (const field of expected) {
    if (!SAFE_MUTATION_FIELD_NAME.test(field)) {
      errors.push(`${prefix}expectedFields contains an unsafe field name ${field}`);
    }
  }
  for (const field of generated) {
    if (!SAFE_MUTATION_FIELD_NAME.test(field)) {
      errors.push(`${prefix}generatedFields contains an unsafe field name ${field}`);
    }
    if (expected.includes(field)) {
      errors.push(`${prefix}generated field ${field} is already a required expected field`);
    }
    if (allowedFields.includes(field)) {
      errors.push(`${prefix}generated field ${field} is also allowed without a validator`);
    }
    validateGeneratedField(errors, field, generatedFields[field], prefix);
  }
  for (const field of allowedFields) {
    if (!SAFE_MUTATION_FIELD_NAME.test(field)) {
      errors.push(`${prefix}allowedFields contains an unsafe field name ${field}`);
    }
    if (expected.includes(field)) {
      errors.push(`${prefix}allowed field ${field} is already a required expected field`);
    }
  }
}

function validateGeneratedField(
  errors: string[],
  field: string,
  validator: CrudMutationGeneratedField,
  prefix: string,
): void {
  if (validator.kind === 'action-time') {
    if (
      validator.offsetMs !== undefined &&
      (!Number.isSafeInteger(validator.offsetMs) ||
        Math.abs(validator.offsetMs) > 366 * 24 * 60 * 60 * 1_000)
    ) {
      errors.push(`${prefix}generated field ${field} has an invalid action-time offset`);
    }
  } else if (validator.kind === 'action-local-calendar-days') {
    if (
      !Number.isSafeInteger(validator.offsetDays) ||
      validator.offsetDays < 1 ||
      validator.offsetDays > 366
    ) {
      errors.push(`${prefix}generated field ${field} has an invalid local calendar-day offset`);
    }
  } else if (
    validator.kind === 'local-day-start' ||
    validator.kind === 'local-day-end' ||
    validator.kind === 'utc-day-start' ||
    validator.kind === 'utc-day-end'
  ) {
    if ('array' in validator.value || 'object' in validator.value) {
      errors.push(`${prefix}generated field ${field} day-boundary source must be scalar`);
    }
  } else if (validator.kind === 'independent-domain-aggregate') {
    const permittedFields: Record<typeof validator.source, readonly string[]> = {
      'customer-statement': ['openingBalance', 'totalDebits', 'totalCredits', 'closingBalance'],
      'supplier-statement': ['openingBalance', 'totalDebits', 'totalCredits', 'closingBalance'],
      'financial-trial-balance': ['resultSummary'],
    };
    if (!permittedFields[validator.source].includes(field)) {
      errors.push(
        `${prefix}generated field ${field} is invalid for independent aggregate ${validator.source}`,
      );
    }
  } else if (
    validator.kind === 'response-secret-digest' ||
    validator.kind === 'response-exact' ||
    validator.kind === 'response-secret-prefix'
  ) {
    if (
      validator.responsePath.length === 0 ||
      validator.responsePath.length > 8 ||
      validator.responsePath.some((segment) => !/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(segment))
    ) {
      errors.push(`${prefix}generated field ${field} has an invalid secret response path`);
    }
    if (
      validator.kind === 'response-secret-prefix' &&
      (!Number.isSafeInteger(validator.length) || validator.length < 1 || validator.length > 64)
    ) {
      errors.push(`${prefix}generated field ${field} has an invalid secret prefix length`);
    }
  } else if (validator.kind === 'request-secret-hash') {
    if (
      validator.requestPath.length === 0 ||
      validator.requestPath.length > 8 ||
      validator.requestPath.some((segment) => !/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(segment))
    ) {
      errors.push(`${prefix}generated field ${field} has an invalid secret request path`);
    }
  } else if (validator.kind === 'timestamp-id') {
    if (!/^[A-Za-z0-9][A-Za-z0-9_.\/-]{0,63}$/.test(validator.prefix)) {
      errors.push(`${prefix}generated field ${field} has an invalid timestamp-id prefix`);
    }
    if (
      validator.actionLocalCalendarYear &&
      !/^[A-Za-z0-9_.\/-]{1,8}$/.test(validator.actionLocalCalendarYear.separator)
    ) {
      errors.push(`${prefix}generated field ${field} has an invalid calendar-year separator`);
    }
    if (
      validator.randomSuffix &&
      (!Number.isSafeInteger(validator.randomSuffix.length) ||
        validator.randomSuffix.length < 1 ||
        validator.randomSuffix.length > 32 ||
        validator.randomSuffix.separator.length > 8)
    ) {
      errors.push(`${prefix}generated field ${field} has an invalid random suffix length`);
    }
  } else if (validator.kind === 'value-with-prefix') {
    if (
      validator.prefix.length < 1 ||
      validator.prefix.length > 64 ||
      (validator.suffix?.length ?? 0) > 64
    ) {
      errors.push(`${prefix}generated field ${field} has an invalid value prefix/suffix`);
    }
  } else if (validator.kind === 'value-with-action-iso-suffix') {
    if (
      validator.separator.length < 1 ||
      validator.separator.length > 16 ||
      (validator.suffix?.length ?? 0) > 32
    ) {
      errors.push(`${prefix}generated field ${field} has an invalid timestamp separator`);
    }
  } else if (validator.kind === 'entity-code') {
    if (!/^[A-Za-z][A-Za-z0-9]{0,63}$/.test(validator.entityType)) {
      errors.push(`${prefix}generated field ${field} has an invalid entityType`);
    }
  } else if (validator.kind === 'scoped-sequence-id') {
    if (
      validator.prefixParts.length === 0 ||
      validator.separator.length < 1 ||
      validator.separator.length > 8 ||
      Object.keys(validator.scope).length === 0 ||
      !Number.isSafeInteger(validator.counter.padding) ||
      validator.counter.padding < 1 ||
      validator.counter.padding > 16
    ) {
      errors.push(`${prefix}generated field ${field} has an invalid scoped sequence contract`);
    }
  }
}
