import { CrudFixtureAuditAttributionStatus } from './crud-evidence-governance';

/**
 * Reviewed legacy mutation paths whose services do not pass an application-
 * policy scope into AuditLogsService. Their tenant snapshot is still exact and
 * immutable, but is recovered from trusted persisted state, so signed evidence
 * must say RESOLVED rather than claiming the stronger EXPLICIT provenance.
 *
 * Keep this as a closed capability allowlist. A new route remains EXPLICIT by
 * default and its live evidence fails until its real provenance is reviewed.
 */
export const CRUD_MUTATION_RESOLVED_AUDIT_CAPABILITY_IDS = Object.freeze([
  'AlertRulesController.activate',
  'AlertRulesController.create',
  'AlertRulesController.deactivate',
  'AlertRulesController.remove',
  'AlertRulesController.update',
  'AllowanceTypesController.create',
  'AllowanceTypesController.remove',
  'AllowanceTypesController.update',
  'ApprovalDelegationsController.cancel',
  'ApprovalDelegationsController.create',
  'ApprovalDelegationsController.remove',
  'ApprovalDelegationsController.update',
  'ApprovalWorkflowsController.activate',
  'ApprovalWorkflowsController.create',
  'ApprovalWorkflowsController.deactivate',
  'ApprovalWorkflowsController.remove',
  'ApprovalWorkflowsController.update',
  'AttendanceController.approve',
  'AttendanceController.create',
  'AttendanceController.remove',
  'AttendanceController.update',
  'AuditEvidencePacksController.addItem',
  'AuditEvidencePacksController.create',
  'AuditEvidencePacksController.markReady',
  'AuditEvidencePacksController.remove',
  'AuditEvidencePacksController.review',
  'AuditEvidencePacksController.update',
  'AutomationRulesController.activate',
  'AutomationRulesController.pause',
  'AutomationRulesController.remove',
  'AutomationRulesController.update',
  'BidComparisonsController.approve',
  'BidComparisonsController.update',
  'CommunicationLogsController.close',
  'CommunicationLogsController.update',
  'CompanyTaxRegistrationsController.create',
  'CompanyTaxRegistrationsController.remove',
  'CompanyTaxRegistrationsController.update',
  'ComplianceDocumentRequirementsController.create',
  'ComplianceDocumentRequirementsController.remove',
  'ComplianceDocumentRequirementsController.update',
  'ComplianceDocumentStatusController.create',
  'ComplianceEventsController.create',
  'ComplianceEventsController.remove',
  'ComplianceEventsController.update',
  'ComplianceObligationsController.complete',
  'ComplianceObligationsController.create',
  'ComplianceObligationsController.remove',
  'ComplianceObligationsController.update',
  'DeductionTypesController.create',
  'DeductionTypesController.remove',
  'DeductionTypesController.update',
  'DepartmentsController.remove',
  'DisciplinaryActionsController.approve',
  'DisciplinaryActionsController.remove',
  'DisciplinaryActionsController.update',
  'EmployeeAllowancesController.create',
  'EmployeeAllowancesController.remove',
  'EmployeeAllowancesController.update',
  'EmployeeAssignmentsController.approveTransfer',
  'EmployeeAssignmentsController.remove',
  'EmployeeAssignmentsController.update',
  'EmployeeDeductionsController.create',
  'EmployeeDeductionsController.remove',
  'EmployeeDeductionsController.update',
  'EmployeesController.approveTermination',
  'EmployeesController.requestTermination',
  'EmploymentContractsController.approve',
  'EmploymentContractsController.create',
  'EmploymentContractsController.remove',
  'EmploymentContractsController.terminate',
  'EmploymentContractsController.update',
  'ExternalMessagesController.create',
  'HrDocumentsController.create',
  'HrDocumentsController.remove',
  'HrDocumentsController.update',
  'LeaveRequestsController.approve',
  'LeaveRequestsController.approveHr',
  'LeaveRequestsController.cancel',
  'LeaveRequestsController.create',
  'LeaveRequestsController.reject',
  'LeaveRequestsController.remove',
  'LeaveRequestsController.submit',
  'LeaveRequestsController.update',
  'LeaveTypesController.create',
  'LeaveTypesController.remove',
  'LeaveTypesController.update',
  'MedicalExamRecordsController.create',
  'MedicalExamRecordsController.remove',
  'MedicalExamRecordsController.update',
  'MessageTemplatesController.create',
  'MessageTemplatesController.remove',
  'MessageTemplatesController.update',
  'MobileMoneyAccountsController.create',
  'MobileMoneyAccountsController.update',
  'OshaRegistrationsController.create',
  'OshaRegistrationsController.remove',
  'OshaRegistrationsController.update',
  'PayrollPeriodsController.create',
  'PayrollPeriodsController.remove',
  'PayrollPeriodsController.update',
  'PerformanceController.create',
  'PerformanceController.remove',
  'PerformanceController.update',
  'PositionsController.remove',
  'PostingRulesController.addLine',
  'PostingRulesController.remove',
  'PostingRulesController.update',
  'PriceListsController.addItem',
  'PriceListsController.updateItem',
  'ProcurementPlansController.approve',
  'ProcurementPlansController.update',
  'SalesCommissionsController.approve',
  'SalesCommissionsController.cancel',
  'SalesCommissionsController.create',
  'SalesCommissionsController.remove',
  'SalesCommissionsController.update',
  'SecurityEventsController.create',
  'SecurityEventsController.resolve',
  'SecurityEventsController.review',
  'SecurityPoliciesController.create',
  'SecurityPoliciesController.remove',
  'SecurityPoliciesController.update',
  'ShiftSchedulesController.create',
  'ShiftSchedulesController.remove',
  'ShiftSchedulesController.update',
  'StatutoryDeductionRulesController.remove',
  'StatutoryDeductionRulesController.update',
  'TasksController.cancel',
  'TasksController.complete',
  'TasksController.create',
  'TasksController.remove',
  'TasksController.update',
  'TaxCodesController.create',
  'TaxCodesController.remove',
  'TaxCodesController.update',
  'TaxFilingPeriodsController.create',
  'TaxFilingPeriodsController.remove',
  'TaxFilingPeriodsController.update',
  'TaxRatesController.approve',
  'TaxRatesController.create',
  'TaxRatesController.deactivate',
  'TaxRatesController.remove',
  'TaxRatesController.update',
  'TaxTransactionsController.create',
  'TaxTransactionsController.post',
  'TaxTransactionsController.remove',
  'TaxTransactionsController.reverse',
  'TaxTransactionsController.update',
  'WorkShiftsController.create',
  'WorkShiftsController.remove',
  'WorkShiftsController.update',
] as const);

const RESOLVED_CAPABILITIES = new Set<string>(CRUD_MUTATION_RESOLVED_AUDIT_CAPABILITY_IDS);

export function crudMutationAuditAttributionStatus(
  capabilityId: string,
): Extract<CrudFixtureAuditAttributionStatus, 'EXPLICIT' | 'RESOLVED'> {
  return RESOLVED_CAPABILITIES.has(capabilityId) ? 'RESOLVED' : 'EXPLICIT';
}
