import {
  AlignmentType,
  Document,
  Footer,
  Header,
  HeadingLevel,
  ImageRun,
  Packer,
  PageNumber,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import * as ExcelJS from 'exceljs';
import { BusinessPdfModel, BusinessPdfOrganization, buildBusinessPdf } from './pdf-builder';

export const DOCUMENT_FORMATS = ['pdf', 'docx', 'xlsx', 'csv', 'txt'] as const;
export type DocumentFormat = (typeof DOCUMENT_FORMATS)[number];
export const DOCUMENT_MIME: Record<DocumentFormat, string> = {
  pdf: 'application/pdf',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  csv: 'text/csv; charset=utf-8',
  txt: 'text/plain; charset=utf-8',
};

export function letterheadLines(org: BusinessPdfOrganization): string[] {
  return [
    org.groupName,
    org.name,
    [org.branchName, org.code].filter(Boolean).join(' · '),
    org.address,
    [org.telephone, org.phone, org.email, org.website].filter(Boolean).join(' · '),
    [
      org.tin && `TIN: ${org.tin}`,
      org.vrn && `VRN: ${org.vrn}`,
      org.registrationNumber && `Reg No: ${org.registrationNumber}`,
    ]
      .filter(Boolean)
      .join(' · '),
  ].filter((line): line is string => Boolean(line));
}

function documentRows(model: BusinessPdfModel): string[][] {
  const rows = letterheadLines(model.organization).map((line) => [line]);
  rows.push(
    [],
    [model.title],
    [model.subtitle ?? ''],
    ['Reference', model.reference],
    ['Status', model.status ?? ''],
    ['Generated', model.generatedAt.toISOString()],
    ...model.meta.map((item) => [item.label, item.value]),
  );
  if (model.compactPartyHeader) {
    const party = model.compactPartyHeader;
    rows.push(
      [party.partyLabel, party.partyName],
      ...party.partyDetails.map((text) => [text]),
      ...party.documentDetails.map((item) => [item.label, item.value]),
    );
  }
  for (const section of model.sections) {
    rows.push(
      [],
      [section.title],
      ...(section.items ?? []).map((item) => [item.label, item.value]),
      ...(section.paragraphs ?? []).map((text) => [text]),
    );
    if (section.table) rows.push(section.table.headers, ...section.table.rows);
    rows.push(
      ...(section.totals ?? []).map((item) => [item.label, item.value]),
      ...(section.signatures ?? []).map((label) => [label, '________________________']),
    );
  }
  rows.push([], ['Generated by ITEMBA OS. Editable exports are copies of the source records.']);
  return rows;
}

/** CSV strings are untrusted, even when originating in business records. */
export function csvCell(value: string): string {
  const safe = /^[\s]*[=+@-]/.test(value) || /^[\t\r\n]/.test(value) ? `'${value}` : value;
  return `"${safe.replace(/"/g, '""')}"`;
}

export async function renderDocument(
  model: BusinessPdfModel,
  format: DocumentFormat,
): Promise<Buffer> {
  if (format === 'pdf') return buildBusinessPdf(model);
  const rows = documentRows(model);
  if (format === 'txt') return Buffer.from(rows.map((row) => row.join('\t')).join('\r\n'), 'utf8');
  if (format === 'csv')
    return Buffer.from(
      '\uFEFF' + rows.map((row) => row.map(csvCell).join(',')).join('\r\n'),
      'utf8',
    );
  if (format === 'xlsx') {
    const book = new ExcelJS.Workbook();
    book.creator = 'ITEMBA OS';
    book.created = model.generatedAt;
    const sheet = book.addWorksheet('Document', {
      pageSetup: {
        paperSize: 9,
        orientation: model.orientation ?? 'portrait',
        fitToPage: true,
        fitToWidth: 1,
        fitToHeight: 0,
      },
    });
    sheet.headerFooter.oddFooter = '&LITEMBA OS&RPage &P of &N';
    const width = Math.max(2, ...rows.map((row) => row.length));
    rows.forEach((values, index) => {
      // Explicit string values cannot become formulas or active hyperlinks.
      const row = sheet.addRow(values.map((value) => String(value)));
      row.alignment = { vertical: 'top', wrapText: true };
      if (values.length === 1 && values[0]) {
        sheet.mergeCells(index + 1, 1, index + 1, width);
        row.font = {
          name: 'Calibri',
          size: index < 2 ? 15 : 11,
          bold: true,
          color: { argb: 'FF18364A' },
        };
      } else row.font = { name: 'Calibri', size: 11 };
    });
    for (const section of model.sections) {
      if (!section.table) continue;
      const first = rows.indexOf(section.table.headers) + 2;
      section.table.rows.forEach((row, offset) => {
        for (const column of section.table?.numericColumns ?? []) {
          const text = row[column];
          // Never round long identifiers/decimal strings beyond Excel's precision.
          if (text && /^-?\d+(\.\d+)?$/.test(text) && text.replace(/[^0-9]/g, '').length <= 15) {
            const cell = sheet.getRow(first + offset).getCell(column + 1);
            cell.value = Number(text);
            if (text.includes('.')) cell.numFmt = `0.${'0'.repeat(text.split('.')[1].length)}`;
          }
        }
      });
    }
    for (let col = 1; col <= width; col++) sheet.getColumn(col).width = col === 1 ? 32 : 24;
    sheet.views = [
      {
        state: 'frozen',
        ySplit: Math.min(letterheadLines(model.organization).length + 1, rows.length),
      },
    ];
    const logo = model.organization.logoImage;
    if (logo && ['image/png', 'image/jpeg'].includes(logo.mimeType)) {
      const image = book.addImage({
        buffer: logo.data as unknown as ExcelJS.Buffer,
        extension: logo.mimeType === 'image/png' ? 'png' : 'jpeg',
      });
      sheet.addImage(image, { tl: { col: width, row: 0 }, ext: { width: 60, height: 60 } });
    }
    return Buffer.from(await book.xlsx.writeBuffer());
  }
  const paragraph = (text: string) => new Paragraph({ text, spacing: { after: 120 } });
  const heading = (text: string) =>
    new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 } });
  const header: Paragraph[] = [];
  const logo = model.organization.logoImage;
  if (logo && ['image/png', 'image/jpeg'].includes(logo.mimeType))
    header.push(
      new Paragraph({
        children: [
          new ImageRun({
            type: logo.mimeType === 'image/png' ? 'png' : 'jpg',
            data: logo.data,
            transformation: { width: 56, height: 56 },
          }),
        ],
      }),
    );
  letterheadLines(model.organization).forEach((line, index) =>
    header.push(
      new Paragraph({
        children: [
          new TextRun({ text: line, bold: index < 2, size: index < 2 ? 26 : 18, color: '18364A' }),
        ],
        spacing: { after: 60 },
      }),
    ),
  );
  const children: (Paragraph | Table)[] = [
    new Paragraph({ text: model.title, heading: HeadingLevel.TITLE }),
    ...(model.subtitle ? [paragraph(model.subtitle)] : []),
    paragraph(`Reference: ${model.reference}${model.status ? ` · ${model.status}` : ''}`),
    ...model.meta.map((item) => paragraph(`${item.label}: ${item.value}`)),
  ];
  if (model.compactPartyHeader) {
    const party = model.compactPartyHeader;
    children.push(
      heading(`${party.partyLabel}: ${party.partyName}`),
      ...party.partyDetails.map(paragraph),
      ...party.documentDetails.map((item) => paragraph(`${item.label}: ${item.value}`)),
    );
  }
  for (const section of model.sections) {
    children.push(
      heading(section.title),
      ...(section.items ?? []).map((item) => paragraph(`${item.label}: ${item.value}`)),
      ...(section.paragraphs ?? []).map(paragraph),
    );
    if (section.table)
      children.push(
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [section.table.headers, ...section.table.rows].map(
            (row, index) =>
              new TableRow({
                tableHeader: index === 0,
                children: row.map(
                  (text) =>
                    new TableCell({
                      children: [
                        new Paragraph({ children: [new TextRun({ text, bold: index === 0 })] }),
                      ],
                      shading: index === 0 ? { fill: 'EEF3F7' } : undefined,
                    }),
                ),
              }),
          ),
        }),
      );
    children.push(
      ...(section.totals ?? []).map((item) => paragraph(`${item.label}: ${item.value}`)),
      ...(section.signatures ?? []).map((label) => paragraph(`${label}: ________________________`)),
    );
  }
  const doc = new Document({
    creator: 'ITEMBA OS',
    title: model.title,
    styles: {
      default: {
        document: { run: { font: 'Calibri', size: 22 }, paragraph: { spacing: { after: 120 } } },
      },
    },
    sections: [
      {
        properties: {
          page: {
            size: { orientation: model.orientation ?? 'portrait' },
            margin: { top: 3000, bottom: 1000, left: 900, right: 900 },
          },
        },
        headers: { default: new Header({ children: header }) },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({ text: 'ITEMBA OS · Page ', size: 18 }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 18 }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });
  return Packer.toBuffer(doc);
}
