// GENERATED by scripts/images/media-manifest.mjs (npm run media:manifest). Do not edit by hand.
// Intrinsic size and a small blur placeholder for every image under public/images, keyed by public src.
import 'server-only';

export type GeneratedMedia = { readonly width: number; readonly height: number; readonly blurDataURL: string };

export const mediaGenerated = {
  "/images/beverages/beverage-stock-crates.webp": {
    width: 1059,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoNABAAA4BaJbACdAEVk8ylzWMAAAD+jXHGCGzAyazUh2gclj3oKdJmezchIoeAhTeeuZObeAqybiOTNMy3VAjO3tVxBozSskayXs97irttdO4A3mYqOHBxBTVAAA==",
  },
  "/images/beverages/beverage-stock-pallets.webp": {
    width: 930,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoMABAAA4BaJbACdAEQXMVcTCAAAOA1tn5hnq5Xjr6DjYs51gbTnNmAojJiIeZBnWmg5YOCKieWunNP93SQZzcepY2zwsjYxkF7T+QJ0Vc9+EB3OmcBbu+SigAAAA==",
  },
  "/images/beverages/liquor-cases.webp": {
    width: 900,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoLABAAA4BaJbACdAEOdu5EoHcAAM3z4fOM/A+oYtBhXVhbcx+/kRxx79qA2M4KbTWJBSlPJf8gTy5zatIuMAH0/x/veRGylTD3E1SWgAA=",
  },
  "/images/beverages/spirits-warehouse-cases.webp": {
    width: 938,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoMABAAA4BaJQBYdh6GRC+tSAD+tCCL/6iBQgMg4djf6oiMrfpV6/rcqb44aLkDAPc2CmluUMfnOumKfFQLRFSGQLWYdzbZCSt0m9uzdY0cQAAA",
  },
  "/images/beverages/westsides-beer-delivery-truck.webp": {
    width: 780,
    height: 1040,
    blurDataURL:
      "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAgCdASoMABAAA4BaJYwC7AYuHbZXBqL1eoAA/vi6aSi/uqoW5C/9iv8X4ezIF+HIP5OE+7pCr36WbE11mX0Wrbp2sIOCuFBYt14i275qyh4yVb1jhX+0i0K8zmWOgAA=",
  },
  "/images/beverages/westsides-cocacola-crates.webp": {
    width: 780,
    height: 1040,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMABAAA4BaJZgCdADcebfjFEAA/uoJNLwm9Fnhh3U01MV4Q4XovIfg3g6iGyu50cfvgjK3GL8GeHHHK2+nESpPn0hOAA==",
  },
  "/images/beverages/westsides-customer-order-truck.webp": {
    width: 780,
    height: 1040,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoMABAAA4BaJQBWACKfAthO+eAA/mozW0n36iUhUHrQChby/VxdaVSolK5mpl8NWpsveRB+Ssuy2cQ9l98WhZDbSQu76UP/1AJ9ZMR+gAA=",
  },
  "/images/beverages/westsides-softdrinks-stacks.webp": {
    width: 780,
    height: 1040,
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMABAAA4BaJZwAAl3DkrF0aYAA/DQBC3Ww4RK5+s04//pKIZWbwhOFkT7OI5FrCwkNGNYWI9wRj06AAAA=",
  },
  "/images/beverages/westsides-softdrinks-warehouse.webp": {
    width: 780,
    height: 1040,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoMABAAA4BaJYwC7AD1dCpjY5MQAP7Q0P6aatYyaB4SnDEkuU/aZwZkr16CODsBOWuTii1npzVGQGS0NkF6qNH1Tgu5bBySGzgQFsgWQAA=",
  },
  "/images/beverages/westsides-stock-overview.webp": {
    width: 1040,
    height: 780,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAwAA4BaJZACdAC8mmCQAAD+0msMHT3SJOt+YnYhsKfXGDbkwRAO3qNaA4Ygl4XZPUd5w7aVXlmzjMNar8+uDjCv+lpWt0l5gAAA",
  },
  "/images/beverages/westsides-warehouse-stock-wide.webp": {
    width: 1040,
    height: 780,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAwAA4BaJYgAAgU3rIzsr4AA/sRZiopYjS+3jGm96JE5jj5wRW2C73OBpGsn+zl6DMxKrXyAJODbmzejafPF2txgAFXTwAA=",
  },
  "/images/company-profile/itemba-group-profile-cover.webp": {
    width: 1600,
    height: 880,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAkAA4BaJbACdAEXFjrgAAD+a/ED1rD1jfPPLvncw/EvLCapW/OrAr8F49z7ZYiiXhYpjI/kW/OZkRzrSGcQgUzh09ZBQf05xdL+jtVRtStaAAA=",
  },
  "/images/fuel-stations/itemba-filling-station-night.webp": {
    width: 1125,
    height: 1500,
    blurDataURL:
      "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMABAAA4BaJZwCdAELT06NlkAA/uodorPVOBYpHFLFGD/xUB6MbuCon/C61I3Tn3nIgY4X09pB6IAA",
  },
  "/images/fuel-stations/itemba-filling-station-wide.webp": {
    width: 1800,
    height: 1350,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAwAA4BaJagCdAD7CGtpUfEAAP7D/cfatmbaOoozW0oCr5dZLfwDVtxyHPwzwqdQuPpp0TAAhdFdO20sIl9HLexMXz+UAAA=",
  },
  "/images/fuel-stations/itemba-mpemba-canopy.webp": {
    width: 900,
    height: 1200,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoMABAAA4BaJbACdAEO9LgeRgFAAN1OvTyZXCWG/2LlBFsBfuSyrd/aBlGr2xb3G9mfq/xEtgKn+XiH8gEWXwqm7sV6b2W6JPW5io/EAAA=",
  },
  "/images/fuel-stations/itemba-mpemba-forecourt.webp": {
    width: 1152,
    height: 864,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAwAA4BaJbACdADcSCJADcAA9ACRoUH6zxKcgoqklOagVraOFWNj5isjw9eMq57igOKGtbGGNx9ASQGs1NetSkuD7Rjr3L9w020T+4N5vYiwQAA=",
  },
  "/images/fuel-stations/itemba-mpemba-front.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQAgCdASoQAAwAA4BaJbACdGuAAsrL4SFrEgAA9lTscD2QXIkDMHxyS4MWThWMg57t0q/Sl7oYvh40mqKckIDl9fDe5yDtNGD8gfGphbWI/dakr7o7nuwAAAA=",
  },
  "/images/fuel-stations/itemba-mpemba-service-yard.webp": {
    width: 1152,
    height: 864,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQAgCdASoQAAwAA4BaJbACdGuAAuHLRArq+gAAzJeWSM/phKYORmYnn2XoGb9hUFL1GwSymtH4kRrPBqFTwrd23McojvCaBYdzYU6+J9o0q7D4vU08G55XAAA=",
  },
  "/images/fuel-stations/itemba-mpemba-station.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoQAAwAA4BaJbACdH8IwABZWmPvsAAA9md59aX29Kt8QAI6bMbaVR5zIPmzVmT+MeyBTd7xG1WCAPmoJFZlcT2TRUaPdVUXAOJaWa7fBmAAAA==",
  },
  "/images/fuel-stations/itemba-mpemba-truck-canopy.webp": {
    width: 1080,
    height: 808,
    blurDataURL:
      "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoQAAwAA4BaJQBOgCHciV5UYmPAAPyO68rHObLrnLPqrsbmb80rG6xGGS52xauX3BLNjyhlQfPzvoc1QXnp1GMyyTHKnu1mlzvsX12494NnPaDcoyCc2mxQ05ZImSFAAAA=",
  },
  "/images/fuel-stations/itemba-mpemba-wide.webp": {
    width: 1152,
    height: 864,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJbACdAEemZzVsgAA+7XKDZ2BFLr+zkIwXMP4h95A2FMcC3m2TEBbvMWaRLw5Qg+eKe8e2zo+m/xzSH2W8+AOF8HbTqjXogAAAA==",
  },
  "/images/fuel-stations/itemba-station-wide-yard.webp": {
    width: 1800,
    height: 1350,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAwAA4BaJagCdAEJS0MdqAAA/tXfdKeeDPWzpTSwUFBxWevWSKUG1tQpXpUaHu2VWJezu8znQcO3M74xivat11jVOMWnoOQAAA==",
  },
  "/images/fuel-stations/itemba-uzunguni-close.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAwAA4BaJagCdGuAAvrVZkzA+AAA/OY1caqBr3qHzD3V23MV1Ejr0s3j975GCnzJJ3vLd3VmCC8iOxVW2nA+6La/o4/7WmSG68/Mm7K9j3dEHNKAAA==",
  },
  "/images/fuel-stations/itemba-uzunguni-forecourt-wide.webp": {
    width: 1152,
    height: 864,
    blurDataURL:
      "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQAgCdASoQAAwAA4BaJbACdEf/ggYwwI7kFAAA/BJ2Q0NNJhJ8BpZgVBkQkxdyCq5p78ySfTc8qOejgTiGaswmfvVKklsRWmAGtGHP7mFpqW73uU3ISr7hiQtM2AUXnmzfkTBAAAA=",
  },
  "/images/fuel-stations/itemba-uzunguni-forecourt.webp": {
    width: 1152,
    height: 864,
    blurDataURL:
      "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAwAA4BaJbACdEf/ggXoE/igAP27WkGJwsLJLjulxMcQ5TFAkD8nEsVD6BtjTKySZVh2W9Pry7+xvW4sqqbOwuY+wd8O9LHU+lM4xuwWj2Id7pmwCi882b8iYIAA",
  },
  "/images/fuel-stations/itemba-uzunguni-front.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAwAA4BaJbACdAEWB1vfxgAA/mpoWLgX3ngXZWJ2xaNlvFnCR0wYfPIN0fbQ2L7ZBXttNSw6V2vX3o8m/UtooKE7OKnwzzId195pf0dqqNqVQAAAAA==",
  },
  "/images/fuel-stations/itemba-uzunguni-pump-island.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwAA4BaJbACdADhG1z7qk8AAPz3sQRt3Ik1dZlDW8p0SPRGT/48uiPb+Q9VBoNf7HDTmhDMSlOhqnGqeBUW8wBXM+xBgszfBXGLE04tyinkrKLtUAAA",
  },
  "/images/fuel-stations/itemba-uzunguni-roadside.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQAAwAA4BaJbACdGuAAs5vve6FWAAA4DfYtjJ83i4oWhjn5LxbP2o1FjteXzjRTLQDHcYJrG4vzL6S2nRn2TLH5LXCGAWmBMqc1KgcrfNXLe3DIGwfePHdImAAAA==",
  },
  "/images/fuel-stations/itemba-uzunguni-station.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAwAA4BaJaACdADbjeXs4AAA/OYaTQ0EQ/uU4DjG0x4yVaBOZ1aP3TxN/1Pm4kWYR9O1ikEm0owRtXX3UqdXMyZCa191wyMHkdYFnReXHpFQAAA=",
  },
  "/images/fuel-stations/itemba-uzunguni-yard-view.webp": {
    width: 1152,
    height: 864,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAwAA4BaJbACdAEe/YB6jp5AAP5fbPkTKH0+8ZUmH5XEZCybObUZNnsl9KADcHBca87r0LLOms6wc3d3USUcAEhLelCyBZ2W68BkMWZIukwAAAA=",
  },
  "/images/hardware/itemba-hardware-paint-stock.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAwAA4BaJQBOgCPPPZ3HVvgAAP7Maz1sx3HGvYly7T2+Ln3KZb6E3I9m42AYD8VXr4DbUdQAslKQvcFWJ+7lneG3XyyU6pmWm7nAMQKQnMwRTQAAAA==",
  },
  "/images/hardware/itemba-hardware-storefront.webp": {
    width: 960,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoMABAAA4BaJZQAAuWtI2TQ/IAA/mz1xtMQ8lz9oDPDRb4TkyEG/TLmjeiOZJ0XYIXvOUI39uwHGv866+klyonZklWa0nlLv1XhGqigFwAAAA==",
  },
  "/images/hospitality/uzunguni-bar-night.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJbACdAEVuk1ejk7QAP7s0KGCuGwF4rC6y4gWE3BfLVcLiNN+x/GBqGaMfLf/8mmZKGNfX/zQM4gBAPa/Lafof+7FxY4UGRD4AA==",
  },
  "/images/hospitality/uzunguni-bar-restaurant.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAwAA4BaJbACdIExELx4yImbxAD+49e45NprbGpD0/dyKMgRIWLHVMhjJf2IRMG3NFjmvvsHXjmDi/jFe9+3uF8AMTlFIvV+79vtvBL8vIIxO8uQ8AAA",
  },
  "/images/hospitality/uzunguni-inn-room.webp": {
    width: 1024,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAwAA4BaJZgC7H8ADnd9GiKgAP7UymLE/KYTFHjtoG7227j42cujZ/guGuMYQ/6X7zmpXi73vikLUjjYANOOUBsie0aW9bKLiBq5sUIeH7OHwAA=",
  },
  "/images/hospitality/uzunguni-lodge-room.webp": {
    width: 600,
    height: 449,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAwAA4BaJbACdAEPhyGQJFekAAD+uD2L4UUXfyD1yxlpvxYqLEgS0kEO0LiRfuO9Xq+zgbPxrXiie2rMzHW/jQqBWgDnid/H56xhS55UtvsifXYAAA==",
  },
  "/images/locations/songwe-region-landscape.webp": {
    width: 2000,
    height: 1125,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJbACdADp02/VqIAA/tRtnIrQ7YPkXL7YUVMXKgUqDAa8uBbmOifVGoGZ2M/+Rmjp4UwcauY80+UAAAA=",
  },
  "/images/logistics/itemba-logistics-tanker-under-canopy.webp": {
    width: 720,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoJABAAA4BaJbACdEf/gbZUWAD+cWiYVN3DcCa8SA5zP7NzI6WtFPl5ILtkG04Xozi0fi+gB4L7ug8vNvETxf8ZoE0vdva+A2a9/3n7cr8kAAAA",
  },
  "/images/logistics/itemba-logistics-truck-front.webp": {
    width: 720,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoJABAAA4BaJbACdADb5CFfiAD+qnrhTX39hg8n9kW4a6m5Jrpnog9j0bfbU2x5PgXVObqHCww8QbDGbPfdxPHk6mF59Hm6x9lYJiA0gAA=",
  },
  "/images/logistics/itemba-logistics-truck-yard.webp": {
    width: 567,
    height: 1008,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoJABAAA4BaJagCdGuAAkbyGFAAAPsOjaGGcgn2cIWQIB+V1fokZLYysGM8wXy5y+n07lbBaoIkW8QiLDPKeirzgyOwlHaDroAAAA==",
  },
  "/images/parking/uzunguni-parking-container-trucks.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAABwAgCdASoQAAwAA4BaJbACdGuAAviAc8uv+A2AAP7c+eI/shv4FkNnSKjXadr5DPxtgvE5t6aFzg/+AH8GPbidMQkm+rPdb+qsZBu7AAA=",
  },
  "/images/parking/uzunguni-parking-truck-line.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAwAA4BaJbACdGuAAvhJqh3TAAD7F6xBwE/Tok9zJzKmdNGBcZhA+iJ6a551BuPYItRPXPTGNNQYrbW4Cq+XAK/p2o77EZ3erWgAAAA=",
  },
  "/images/parking/uzunguni-parking-yard-overview.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAwAA4BaJbACdAEKTEZ2Q9AA/NMGz0LnB6BqSu8aonNeigN+HXa1FcKpCvjuOKZoPEzbzzce9NKox3413NiS7962LLpj6Dooz4wBJlo1okgAAAA=",
  },
  "/images/parking/uzunguni-parking-yard-trucks.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAwAA4BaJbACdAD0u2TG01oMAOA1jlXRbzPQbKNCasI2h8GW8RwWFTZT7p/EO7Q8KfrLAqm5jwV/bUzbJtVtlvzs7rQzuFyw3WzTRIwfeAAA",
  },
  "/images/real-estate/modern-african-estate-construction-card.webp": {
    width: 1400,
    height: 1050,
    blurDataURL:
      "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACQAgCdASoQAAwAA4BaJQBOkBvk/xa/+cAxFPn4AAD+qeoYn7OVggV6H1pH0kEImCcBdnoRmdJMMOF9zhwXDh4m63qnZRRipfyfbGvlEoCIhsoJNwdY967pKKzfRL7Fe1Rd8wu4QgeS3TrfHmOAAA==",
  },
  "/images/real-estate/modern-african-estate-construction-wide.webp": {
    width: 1800,
    height: 1012,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAkAA4BaJQBOj+AQThh6wK2OAAD+oynsFMRahTaFP3i9f30z4WnVHXhX3ijPQNcX7Obtj2sebpFtFYhKpMP8xJKG/eXTic+wzny4knZHe83bScSBgAAA",
  },
  "/images/real-estate/modern-african-estate-construction.webp": {
    width: 1440,
    height: 1800,
    blurDataURL:
      "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwAgCdASoNABAAA4BaJYgCdEf/i19ZLS4vAAD+M7Gu7965JaYzR3gDaFaqdgnzEILrRcT7K1vLCpqdOfPovuF0p8ia21r0ckZ98sASSE4Y0cjmsUyljQPyHSZfgKh9BXCR/H/kHLgKnIQAAAA=",
  },
  "/images/real-estate/modern-african-housing-development-wide.webp": {
    width: 1800,
    height: 1012,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAQCdASoQAAkAA4BaJbAC7ABqMluAAP4xgEPtY3mAWWWNAv9NoVdKgUzopI/ifEKIVDt46TRTf0kUJunjnGm+3+QoZ9vScNvGt1h5U1QzYwJfagAAAA==",
  },
  "/images/real-estate/modern-african-housing-development.webp": {
    width: 1800,
    height: 1350,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQAAwAA4BaJbAC7AYqXUW6DrAA/nhQxzNOPY/xk9G2hmjQTJTe4xUh6mMhnCI0VWHCJhvGV2I01OW8eckN3olRc7V7NuUxS+mvrDBmE36f1W58fsB6DuHY+eAAAA==",
  },
  "/images/real-estate/modern-tanzania-white-villa-wide.webp": {
    width: 1800,
    height: 1012,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJQBOgCKsN0PhywAA/uI2k7ctH/PNve/1ZyJiiLNHAFqg9b8o15VXQMWjaRmZHh9/kCd8FdkBiiJSNvk/Suywy68qF3fFetr1QAAA",
  },
  "/images/real-estate/modern-tanzania-white-villa.webp": {
    width: 1200,
    height: 1800,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABwAgCdASoLABAAA4BaJZACdAYv1qy5cR1YDtcAAP7F+/nXhVJDnzFoYqqLf92p3k1fbDunpkP1aRbo94dgx1YibZKJ9XX5naL2cYYM1ZD89IH+enHbauRk/x+1FSAVUHsAAA==",
  },
  "/images/real-estate/zanzibar-residential-houses-aerial-wide.webp": {
    width: 1800,
    height: 1012,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAkAA4BaJQBOgCB/SQK2CkAA/uwPYnnXX7eNTpfEanbVHxfiubAKWmjYyHIie9VR0S6ZH2VvhZMzib0MOgHpvS8hOkPa+ojbwSJwkAm/iBCWgAA=",
  },
  "/images/real-estate/zanzibar-residential-houses-aerial.webp": {
    width: 1200,
    height: 1800,
    blurDataURL:
      "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAgCdASoLABAAA4BaJZQC7AYu5vrizWiDgAAA/uwRTQNsTK/OBB+0ZbwkfoOhrH3Q0FeqGv69CLUbNMXNz0MRY5d9mHeqrjqhM/exRfPcWk/qU6pwyL4YI9egScqAAAA=",
  },
} as const satisfies Record<string, GeneratedMedia>;

export type GeneratedMediaSrc = keyof typeof mediaGenerated;
