// GENERATED by scripts/images/media-manifest.mjs (npm run media:manifest). Do not edit by hand.
// Intrinsic size and a small blur placeholder for every image under public/images, keyed by public src.
import 'server-only';

export type GeneratedMedia = { readonly width: number; readonly height: number; readonly blurDataURL: string };

export const mediaGenerated = {
  "/images/beverages/beverage-stock-crates.webp": {
    width: 1059,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoNABAAA4BaJagCdAD6wFB+JgAA/dLe/qzW7tmLGyO2n6pEG3fyxF6En2OvpWWtccN64DXP0vJwNOFR46PrauqtI0LgAA==",
  },
  "/images/beverages/beverage-stock-pallets.webp": {
    width: 930,
    height: 1242,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoMABAAA4BaJbACdACec4ZgAAD8Z9FOZpDwlVRNneDgSsikz1kiNpUbOdBDY2Gn4ebbHV+vzS0o8clx+Jn79DtY081RgS1iPFlpcd1lUAAAAA==",
  },
  "/images/beverages/liquor-cases.webp": {
    width: 900,
    height: 1204,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoMABAAA4BaJbACdADc+K26lZuwAP6Z7j3yR99oZqQJLIn8BT0GcedX4dX+QSajQwYdBF4tRyKmv6+5X4Hv3QePfl6i6QAA",
  },
  "/images/beverages/spirits-warehouse-cases.webp": {
    width: 938,
    height: 1252,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoMABAAA4BaJYwC7ADcAG9apQAA/rOsJ+SlUweMD//pPD4GX9Z8w3MOx7oStSEg5AM53AVK3xbl4yubQOFtZSm43q6x8ACg8iHgAAAA",
  },
  "/images/beverages/westsides-beer-delivery-truck.webp": {
    width: 780,
    height: 1040,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoMABAAA4BaJZwAAjl8cxwAAP74umkoiyrrYysdkgvGVdV7BCmv8aTFzipWzeGIjQtbCQqO0fWc/EmN9Ftpfel9tgpnb9LwKFud4JMuAAA=",
  },
  "/images/beverages/westsides-cocacola-crates.webp": {
    width: 780,
    height: 1040,
    blurDataURL:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoMABAAA4BaJQBdgBuVmHcjg+QA/uoFfT5AiO7qkD9iZnSoosJKe1Tae6petecqI5CUEiWjFAA=",
  },
  "/images/beverages/westsides-customer-order-truck.webp": {
    width: 780,
    height: 1040,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoMABAAA4BaJZQCsAEQzG7PrQAA/OzDvOZ3DnVGb7kftCeGtOzVusPEgHcbf9YrQwOFNYc2RZcgDylyHO7CKZkYAS6nzAAA",
  },
  "/images/beverages/westsides-softdrinks-stacks.webp": {
    width: 780,
    height: 1040,
    blurDataURL:
      "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoMABAAA4BaJZwAAt0LC8PCLgoAAPa+Z+XE2JRhH2ogVLEIIuUhvuGTzOhFQtpA2A4jkyrIa+nQAA==",
  },
  "/images/beverages/westsides-softdrinks-warehouse.webp": {
    width: 780,
    height: 1040,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMABAAA4BaJZQC7AERAw/scgAA/sBDFsZGK+qq+Vr6rTlurD8Aaht/H/lEM2mJFuiyBrl7ivXW8iD6FIANIAAA",
  },
  "/images/beverages/westsides-stock-overview.webp": {
    width: 1040,
    height: 780,
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAwAA4BaJQBYdheVOwMw4AD+wcf8tFjsCqnKDKZu5EOxTB5+Va+Eno9d0cNHJZePYcOPFxnlSVitAAA=",
  },
  "/images/beverages/westsides-warehouse-stock-wide.webp": {
    width: 1040,
    height: 780,
    blurDataURL:
      "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAwAA4BaJYwAAjPDPgLEeAD+jgXQN5iRSpjwTUNLIIJVp4eEgssMvyAzCqxPejS/zjCDtOMsoAAA",
  },
  "/images/company-profile/itemba-group-profile-cover.webp": {
    width: 1280,
    height: 704,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJYgCdADwJ89kgAD+BL1akBrlqHnw3wefFPxcOkaz7ayE18GhVOVuMIfUjbipVQw8e7vDZomEAAAA",
  },
  "/images/fuel-stations/itemba-filling-station-night.webp": {
    width: 1200,
    height: 1600,
    blurDataURL:
      "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoMABAAA4BaJZwAAt0GXPOFV4UAAP7mU7PvLmcAmvFtSaf5L7aPxAwbhunAel4ouZ1xAAAA",
  },
  "/images/fuel-stations/itemba-filling-station-wide.webp": {
    width: 2400,
    height: 1800,
    blurDataURL:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoQAAwAA4BaJQBOgCIcE1HZIAD+r3BwCmUgoO/QAutJUS39drjwPIgck3yVauYCZlrs+5h40AA=",
  },
  "/images/fuel-stations/itemba-mpemba-24-hours-dusk.webp": {
    width: 2400,
    height: 1800,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAQCdASoQAAwAA4BaJZQC06DyBgAA+p3PwzmHeardiTf3/x6RgHdz01l4e1q2IDxemdlLgGK8yaq8YftpU8YJeldnORFzfHptQeErAAA=",
  },
  "/images/fuel-stations/itemba-mpemba-canopy.webp": {
    width: 960,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMABAAA4BaJagCdAC9xM+UBYAA3WfUoN2zEBOQsBPN75GoPG5YEzqtDf5op+zj8PXXeN51BrVOW1VheAA=",
  },
  "/images/fuel-stations/itemba-mpemba-coach-canopy.webp": {
    width: 2400,
    height: 1200,
    blurDataURL:
      "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoQAAgAA4BaJZQCdACewAAA/t/mlzIeiDoy708Rf+dRoStycRsCnjIihhuyPbjNF+DZ5HgA",
  },
  "/images/fuel-stations/itemba-mpemba-forecourt.webp": {
    width: 1152,
    height: 864,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAwAA4BaJZACdGuAAkbGZTIwAPQAkZ7Ux0CG8/pHt4Xp4VX/JirVnGqzXupHistzoRZE6SCGVbvp4Mk3rnN4ZPNZn8AAAAA=",
  },
  "/images/fuel-stations/itemba-mpemba-front.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAwAA4BaJZACdGuAAr6C42wAAMwDHvjdtiwYeZk6p6f7Q6t2ro3PSmgZcdvvvuwjfx+7wyO3S3VjQoTHjNYsUuYAAA==",
  },
  "/images/fuel-stations/itemba-mpemba-hero.webp": {
    width: 2400,
    height: 1694,
    blurDataURL:
      "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoQAAsAA4BaJQBOgCPp1T1b4EgAAP7IowBms8vXjICgQorv3aFzKqkZV89GLWB2pLJ254anYI3yQAAA",
  },
  "/images/fuel-stations/itemba-mpemba-service-yard.webp": {
    width: 1152,
    height: 864,
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoQAAwAA4BaJZACdGuAApOdMYeAAPRLKFV7Ujeb8LaO+UAihQsKOprSPU2brgFDHULmcjxxedxpowAF3gYAAA==",
  },
  "/images/fuel-stations/itemba-mpemba-station.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAwAA4BaJZACdGuAAr6C42wAAMwDHvjdtiwYeZk6p6f7Q6t2ro3PSmgZcdvvvuwjfx+7wyO3S3VjQoTHjNYsUuYAAA==",
  },
  "/images/fuel-stations/itemba-mpemba-truck-canopy.webp": {
    width: 976,
    height: 730,
    blurDataURL:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAwAA4BaJYwCdAYvXvqcMI4RAADgM36yj+wk7Iq+dwV2x6X9Q3zId6DjR3p5Vp+JLK65rWPZxAZoHJzUeEn9T9F1L1fzArxUzbjJdyy6U9J+8E7CXyhiSQAAAA==",
  },
  "/images/fuel-stations/itemba-mpemba-wide.webp": {
    width: 1152,
    height: 864,
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAABQAgCdASoQAAwAA4BaJZgCdGuAAvgH8LYSXAAA88s95L1IdOyBi452eWOWoJGuDAhw++bl0zXOp8rr2XlHaEGSQAAAAA==",
  },
  "/images/fuel-stations/itemba-station-wide-yard.webp": {
    width: 2400,
    height: 1800,
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAwAA4BaJYgCdAEDEHDmgAD+xxcfEJJEm9j4vqd7oIpIebRgPNADMWX/B0it145H3TettKvhqdgmVTEAAA==",
  },
  "/images/fuel-stations/itemba-uzunguni-close.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwAA4BaJQBOgCPwnPcO2UAA/mFkKmI4TnhXQE2zj/oV8wQXBGzr9tLPf253yeG+CvThp3wXP87gQ4AAAA==",
  },
  "/images/fuel-stations/itemba-uzunguni-forecourt-wide.webp": {
    width: 1152,
    height: 580,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABQAgCdASoQAAgAA4BaJZACdGuAAvgKRk2cJkAA9m+HkOh5DNg168sF4jvAOwB9wEBUWGgPktSNTCNH9fEHRty0ZuVwS+MAAAA=",
  },
  "/images/fuel-stations/itemba-uzunguni-forecourt.webp": {
    width: 1152,
    height: 864,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAwAA4BaJZACdGuAAvfnaHsAAPZwbY0IsnzxFKoLe+ePqasxS+Q96praAxF9KZzejjTiwpaERt7kAqKCtJ9NxpbKX3OwAAA=",
  },
  "/images/fuel-stations/itemba-uzunguni-front.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAwAA4BaJYgCdAEXy9oJ/AAA/gS9Wo73MGwt2R+yOTr1FQGAoWuvNSjcFdYsOREi6nHSE39lRoFvvPmDTOnNoAA=",
  },
  "/images/fuel-stations/itemba-uzunguni-pump-island.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAwAA4BaJQBOgBwsz/rEPAAA/mi46BfoUaf7oYtKHeSZQMe8OAwboItSuFck9qOl8Gnl0WwoX2zpBcoHuUAA",
  },
  "/images/fuel-stations/itemba-uzunguni-roadside.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAwAA4BaJYgCdAEHFYegAPhjw1MYYlQ/OcKG+Y3CcBZ/7UPKdqGyf/wJ8Sg5m6k6fbOexAthNTVVO79auNb7fJjgK1V/kzRyAAAA",
  },
  "/images/fuel-stations/itemba-uzunguni-station.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwAA4BaJQBOgCPwnPcO2UAA/mFkKmI4TnhXQE2zj/oV8wQXBGzr9tLPf253yeG+CvThp3wXP87gQ4AAAA==",
  },
  "/images/fuel-stations/itemba-uzunguni-yard-view.webp": {
    width: 1152,
    height: 864,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAwAA4BaJZACdADcHsH0AAD+VepPYXBiBi0F9uHaFS8en+kbIW2/szm0fUr6uOgrUjJ8YA7RXI3aUlPwchIhY2EPmABAAAA=",
  },
  "/images/hardware/itemba-hardware-paint-stock.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAwAA4BaJZQCdAEeg9SutvgA/nNFLdY2sdFqy1PzKmjyViHyAGltU5g4MDJ3CXBQ+xUAKuK4KWFhllPFvAklydsVkzhSwAxwnhwKAAA=",
  },
  "/images/hardware/itemba-hardware-storefront.webp": {
    width: 960,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoMABAAA4BaJZwAAueBS8Bkc7AAAP6b82qzuw9L/QdmS+ofEdffyVbTerGzLRpyDzZSEbp7qViC79wH+mV/LjoKDN629OigIAAAAA==",
  },
  "/images/hospitality/uzunguni-bar-night.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAwAA4BaJbACdAD0bg3FgAD+2fV4vsVpeNwXyfVUPJ+4Ej6GRmAHljPjP/iMa9r/djRT7xIpgQHi4seTfi3GAAA=",
  },
  "/images/hospitality/uzunguni-bar-restaurant.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAwAA4BaJZACdACRVfuR4AD+uxleUGe0zLx8rKmCcnncwox5lhg5fv+huotSRouq3V1y0uFCJ8My7F7DYSAFO0G+EPjpgAAAAA==",
  },
  "/images/hospitality/uzunguni-inn-room.webp": {
    width: 1024,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAwAA4BaJYgAAf5tqcpdSAAA/udLbpFjOWu7CRcADDiefwBwQsm8nRujqJ0PotSMD2PkJq0MhaEkV0qbQ8X+hBiUjRJnvgAAAA==",
  },
  "/images/hospitality/uzunguni-lodge-room.webp": {
    width: 600,
    height: 449,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAwAA4BaJagCdAEPh4utigwowAD+uDwW+l89DsmT7uFYYZS/HS1TQ7xl1LnB93islp6HHrPikC8kurtSVo3tT7mdzKc3vtrDCfJy2oqRFQAA",
  },
  "/images/locations/songwe-region-landscape.webp": {
    width: 2000,
    height: 1125,
    blurDataURL:
      "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkAA4BaJbACdADp02ZrWAD+1GvOrWvC9aM043wrt2jbvnKjRNmLDGN693uAvg8wB76Nx54cgAAA",
  },
  "/images/logistics/itemba-logistics-tanker-under-canopy.webp": {
    width: 720,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoJABAAA4BaJbACdAEON6AAAP2MuzkkNb0AyUn+xISLO30U/N053y+BBUuHypbL0B0Vpk2c9TGghPnUE5ZWyHp069vxIgAA",
  },
  "/images/logistics/itemba-logistics-truck-front.webp": {
    width: 720,
    height: 1280,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoJABAAA4BaJYgCdAEU8nFRvfwAAP2j6E5prE8P+FFzUdSIdJ7HPhu9KltUxI1ZxHJEg6qMeeQd7R3ogMwYQ0AAAAA=",
  },
  "/images/logistics/itemba-logistics-truck-yard.webp": {
    width: 567,
    height: 1008,
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoJABAAA4BaJZACdADdLk7Gt4AA9B/6fhxlbMXMJVsVJOvV84e5MzscvYDPvRQZyLCEKWmTpeseqHgyRuYAAA==",
  },
  "/images/parking/uzunguni-parking-container-trucks.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwAA4BaJYgCdAEesRtaDAAA/qMoUSxnDgGht7qZ4YqZOqbD7RotXm6ylYPuZu/P1eq2hSn2Jq+OfgAAAA==",
  },
  "/images/parking/uzunguni-parking-truck-line.webp": {
    width: 1280,
    height: 620,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABQAgCdASoQAAgAA4BaJZACdH8IwABbw+qnFYAA8TtRUsdtshyA5CsxKNNBnmqs55dlaBvp5IgM78lCucrdtQqZrCmBakax9N+AAA==",
  },
  "/images/parking/uzunguni-parking-yard-overview.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoQAAwAA4BaJYgCdAEKS/1LeBYAAP36wB0AAhh+7PYcavtnVhg5ewZs3YjsV84VNKYQRkIQ5X/Dg2EcS/HK9iIAAAA=",
  },
  "/images/parking/uzunguni-parking-yard-trucks.webp": {
    width: 1280,
    height: 960,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAwAA4BaJZACdADwJ8P9VAD4Yhx9T9mTtF09FVicBZT7w/7LE/+N8lOLn3zgHBOW57YWhy0ArNWV13tAFmaQIfrgAA==",
  },
  "/images/real-estate/modern-african-estate-construction-card.webp": {
    width: 1400,
    height: 1050,
    blurDataURL:
      "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAgCdASoQAAwAA4BaJYwCdIIpJ/i1+s4Bieu2c6AAAP6DxwlfdREBw+h9aR841qcQKoA5jbTZ4J2rcfKwse4NIBG720+dniKBKrE09ZqbIMJTBlZDawczukongo7lw4Th4bE6/j1s1vZWQAAAAA==",
  },
  "/images/real-estate/modern-african-estate-construction-wide.webp": {
    width: 1600,
    height: 900,
    blurDataURL:
      "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAkAA4BaJYwCdH8AGJwjdQ9QAP54rrLaFrX9iRky9E4EfroYLYidEfqKZ6VzCIr9hksRS0U/wR8YBMWsB9YYvsIRk1NxHHrfT+jzDyQhHdYwYAA=",
  },
  "/images/real-estate/modern-african-estate-construction.webp": {
    width: 1280,
    height: 1600,
    blurDataURL:
      "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAQCdASoNABAAA4BaJQBOgCBraN45AAD9dqiD9ePWqLOsP/y6AtzOwHHrLS6/3J/j1j+folaxYtSOP/tM6USvoRBmP9I4ZlBATWFGs4UKKHIz1K1JEMjYBlyAJ+9t8Ac5NEAA",
  },
  "/images/real-estate/modern-african-housing-development-wide.webp": {
    width: 1600,
    height: 900,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACQAQCdASoQAAkAA4BaJZAAASLIngAA/XBvK4gX4+qdRsA1x3lFna0mx+Dk6659EM+y2OalhGEIKKPPy11IfQAXPMJaQOe/9B2dxpnwgEcOEAAA",
  },
  "/images/real-estate/modern-african-housing-development.webp": {
    width: 1600,
    height: 1200,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAwAA4BaJZgC7AYqNUfjQMQGYAD+JZlErrQ5de0kaBNRvuAM47zjXCg1r+pwK/oZ8+KMo/Q05c0K68T+KWwBvprrwEZpdocuav2DJxBZM7SRH4AAAA==",
  },
  "/images/real-estate/modern-tanzania-white-villa-wide.webp": {
    width: 1600,
    height: 900,
    blurDataURL:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkAA4BaJQBOgCDplRUOAAD+4jaTty0jNGXJ1HV3K09FetAfGEHO/Zopc8cjEwjIev43DBkc/yt7oBOw6occbXbAlDg/y7RTPFimrx7AAA==",
  },
  "/images/real-estate/modern-tanzania-white-villa.webp": {
    width: 1067,
    height: 1600,
    blurDataURL:
      "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoLABAAA4BaJQBOgCBv094sL4AOIAD+xfv7sZ1qPgxLr7Mwu8adi31RD1yihhWTfXzgKnplJWRPf5jW0k8eVVK7kjNZ+g26/ZJcPXzBEgfBBbQMhjql0cAA",
  },
  "/images/real-estate/zanzibar-residential-houses-aerial-wide.webp": {
    width: 1600,
    height: 900,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAkAA4BaJYwCsAED+kNcS0AA/ukEOphSTnttjb0hBeTgGQqCyyhkro4yVvU3rUnb7WaP9DzTHB5Z/+5oYYi4LfHUS1X+ZNTbPlb0MI6C0gAA",
  },
  "/images/real-estate/zanzibar-residential-houses-aerial.webp": {
    width: 1067,
    height: 1600,
    blurDataURL:
      "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoLABAAA4BaJZQAD5COtMAZL/oA/ukGfF8c5QHjiMTBz1P5NDl1hanTO/UircAMeR2kX1q23qWFSl7N7Vg3LAm5fFVEpSEmfRm/5cUxV+8o3Wt694uAAA==",
  },
} as const satisfies Record<string, GeneratedMedia>;

export type GeneratedMediaSrc = keyof typeof mediaGenerated;
