export const REPORTS = [
  {
    id: 'customers',
    name: 'Customer reports',
    description: 'Activity, statements, payments and overdue balances.',
    source: 'Sales Desk',
    permission: 'sales_desk.view',
    path: '/sales-desk/overview',
    directory: '/sales-desk/directory',
    mode: 'customers',
  },
  {
    id: 'suppliers',
    name: 'Supplier reports',
    description: 'Purchases, statements, payments and what you owe.',
    source: 'Invoice Desk',
    permission: 'invoice_desk.view',
    path: '/invoice-desk/overview',
    directory: '/invoice-desk/directory',
    mode: 'suppliers',
  },
  {
    id: 'sales',
    name: 'Sales report',
    description: 'Sales, payments and outstanding amounts.',
    source: 'Sales Desk',
    permission: 'sales_desk.view',
    path: '/sales-desk/sales',
    directory: '/sales-desk/directory',
    mode: 'sales',
  },
  {
    id: 'purchases',
    name: 'Purchase report',
    description: 'Purchase invoices and their payment status.',
    source: 'Invoice Desk',
    permission: 'invoice_desk.view',
    path: '/invoice-desk/invoices',
    directory: '/invoice-desk/directory',
    mode: 'purchases',
  },
  {
    id: 'expenses',
    name: 'Expense report',
    description: 'Spending by category, payee and date.',
    source: 'Cash Desk',
    permission: 'cash_desk.view',
    path: '/cash-desk/expenses',
    directory: '/cash-desk/directory',
    mode: 'expenses',
  },
  {
    id: 'cash',
    name: 'Cash movements',
    description: 'Receipts, transfers and money paid out.',
    source: 'Cash Desk',
    permission: 'cash_desk.view',
    path: '/cash-desk/movements',
    directory: '/cash-desk/directory',
    mode: 'cash',
  },
  {
    id: 'loans',
    name: 'Intercompany loans',
    description: 'Money lent within the group and balances due.',
    source: 'Cash Desk',
    permission: 'cash_desk.view',
    path: '/cash-desk/loans',
    directory: '/cash-desk/directory',
    mode: 'loans',
  },
] as const;
export type ReportDefinition = (typeof REPORTS)[number];
export const MORE_REPORTS = [
  {
    name: 'Inventory',
    description: 'Stock value, movements and low stock.',
    href: '/inventory?tab=reports',
    permission: 'operations.reports.view',
  },
  {
    name: 'People & payroll',
    description: 'Employees, attendance, leave and payroll.',
    href: '/hr/reports',
    permission: 'hr.reports.view',
  },
  {
    name: 'Financial statements',
    description: 'Profit and loss, cash flow and account balances.',
    href: '/finance/reports',
    permission: 'finance.reports.view',
  },
  {
    name: 'ERP sales & purchases',
    description: 'Transactions recorded in ITEMBA-R operations.',
    href: '/operations/reports',
    permission: 'operations.reports.view',
  },
  {
    name: 'Westsides',
    description: 'Westsides customers, products and trading reports.',
    href: '/westsides/reports',
    permission: 'westsides.reports.view',
  },
] as const;
