#!/usr/bin/env bash
#
# ITEMBA-R one-shot relaunch / provisioning script for a fresh Ubuntu droplet.
#
#   - installs Docker + the compose plugin (if missing)
#   - adds swap so the two Next.js builds don't OOM on a small droplet
#   - generates fresh production secrets ON THIS HOST and writes ./.env.production
#     (secrets never leave the droplet; ./.env.production is gitignored)
#   - builds + starts the full production stack (migrations run automatically)
#   - runs the idempotent seed (group/companies/roles/admin user)
#   - installs a nightly pg_dump backup cron + takes one backup now
#
# Usage (from the repo root, as root or a sudo user):
#   DOMAIN=itembagrouptz.com bash deploy/relaunch/deploy.sh
#
# Re-running is safe: existing .env.production + secrets are preserved, the stack is
# rebuilt/updated, and the seed upserts.

set -euo pipefail

# ----------------------------------------------------------------------------
# Config (override via env: DOMAIN=... ACME_EMAIL=... bash deploy/relaunch/deploy.sh)
# ----------------------------------------------------------------------------
DOMAIN="${DOMAIN:-itembagrouptz.com}"
ACME_EMAIL="${ACME_EMAIL:-info@${DOMAIN}}"
COMPOSE_FILE="docker-compose.production.yml"
ENV_FILE=".env.production"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_DIR"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

gen_secret() { openssl rand -base64 48 | tr -d '\n/+=' | cut -c1-48; }
gen_password() { openssl rand -base64 36 | tr -d '\n/+=' | cut -c1-28; }
ensure_env_default() {
  local key="$1"
  local value="$2"
  if ! grep -q "^${key}=" "$ENV_FILE"; then
    printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  fi
}

# ----------------------------------------------------------------------------
# 1. Docker + compose plugin
# ----------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker Engine + compose plugin"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg openssl git
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
else
  log "Docker already installed: $(docker --version)"
fi

if command -v ufw >/dev/null 2>&1; then
  log "Configuring UFW for SSH, HTTP, and HTTPS"
  ufw allow OpenSSH >/dev/null || true
  ufw allow 80/tcp >/dev/null || true
  ufw allow 443/tcp >/dev/null || true
  ufw --force enable >/dev/null || true
fi

# ----------------------------------------------------------------------------
# 2. Swap (so the Next.js builds don't OOM on a 4 GB droplet)
# ----------------------------------------------------------------------------
TOTAL_RAM_MB=$(free -m | awk '/^Mem:/{print $2}')
if [ "${TOTAL_RAM_MB:-0}" -lt 7000 ] && [ ! -f /swapfile ]; then
  log "Adding 4 GB swap (RAM is ${TOTAL_RAM_MB} MB)"
  fallocate -l 4G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=4096
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

# ----------------------------------------------------------------------------
# 3. Generate .env.production with fresh secrets (only if it does not already exist)
# ----------------------------------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
  ADMIN_PASSWORD="$(gen_password)"
  log "Generating fresh production secrets -> ${ENV_FILE}"
  cat > "$ENV_FILE" <<ENVEOF
# Generated by deploy/relaunch/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# SECRET — never commit. Back this file up somewhere safe (a password manager).

# --- Database ---
POSTGRES_DB=itemba_r
POSTGRES_USER=itemba_user
POSTGRES_PASSWORD=$(gen_secret)

# --- Redis ---
REDIS_PASSWORD=$(gen_secret)

# --- Auth / crypto (each must be distinct) ---
JWT_ACCESS_SECRET=$(gen_secret)
JWT_REFRESH_SECRET=$(gen_secret)
TWO_FACTOR_ENCRYPTION_KEY=$(gen_secret)
REFRESH_TOKEN_PEPPER=$(gen_secret)
APP_ENCRYPTION_KEY=$(gen_secret)
JWT_ACCESS_EXPIRES_IN=never
JWT_REFRESH_EXPIRES_IN=never
AUTH_COOKIE_MAX_AGE_SECONDS=315360000

# --- Domain / TLS (Caddy) ---
ACME_EMAIL=${ACME_EMAIL}
APP_HOST=app.${DOMAIN}
API_HOST=api.${DOMAIN}
WEBSITE_HOST=${DOMAIN}
WEBSITE_WWW_HOST=www.${DOMAIN}
FUELGRID_APP_HOST=fuelgrid.${DOMAIN}
FUELGRID_API_HOST=api.fuelgrid.${DOMAIN}
SHARED_EDGE_NETWORK=itemba_shared_edge

# --- App URLs ---
FRONTEND_URL=https://app.${DOMAIN}
APP_URL=https://app.${DOMAIN}
CORS_ORIGIN=https://app.${DOMAIN}
NEXT_PUBLIC_API_URL=https://api.${DOMAIN}/api/v1
NEXT_PUBLIC_WEBSITE_URL=https://${DOMAIN}
BACKEND_INTERNAL_URL=http://backend:3001/api/v1
FUELGRID_APP_URL=https://fuelgrid.${DOMAIN}
FUELGRID_HEALTH_URL=https://api.fuelgrid.${DOMAIN}/readyz

# --- Misc ---
JOB_WORKER_ENABLED=true
SEED_ADMIN_EMAIL=admin@${DOMAIN}
SEED_ADMIN_PASSWORD=${ADMIN_PASSWORD}
SEED_DEMO_DATA=true

# --- Optional integrations (fill in if/when needed) ---
# SMTP_HOST=
# SMTP_PORT=587
# SMTP_USER=
# SMTP_PASS=
# SMTP_FROM=
# MPESA_CONSUMER_KEY=
# MPESA_CONSUMER_SECRET=
# MPESA_SHORTCODE=
# MPESA_PASSKEY=
ENVEOF
  chmod 600 "$ENV_FILE"
  log "${ENV_FILE} created. BACK IT UP — these secrets cannot be recovered."
else
  log "${ENV_FILE} already exists — leaving it untouched"
fi

# These are non-secret topology defaults added after the original production
# bootstrap. Preserve any operator override while making old .env files ready
# for the shared ITEMBA-R/FuelGrid droplet layout.
ensure_env_default SHARED_EDGE_NETWORK itemba_shared_edge
ensure_env_default FUELGRID_APP_HOST "fuelgrid.${DOMAIN}"
ensure_env_default FUELGRID_API_HOST "api.fuelgrid.${DOMAIN}"
ensure_env_default FUELGRID_APP_URL "https://fuelgrid.${DOMAIN}"
ensure_env_default FUELGRID_HEALTH_URL "https://api.fuelgrid.${DOMAIN}/readyz"

SHARED_EDGE_NETWORK="$(sed -n 's/^SHARED_EDGE_NETWORK=//p' "$ENV_FILE" | tail -n1)"
SHARED_EDGE_NETWORK="${SHARED_EDGE_NETWORK:-itemba_shared_edge}"
log "Ensuring shared application edge network: ${SHARED_EDGE_NETWORK}"
docker network inspect "$SHARED_EDGE_NETWORK" >/dev/null 2>&1 \
  || docker network create "$SHARED_EDGE_NETWORK"

# ----------------------------------------------------------------------------
# 4. Build + start the stack (migrations run via the backend-migrate one-shot)
# ----------------------------------------------------------------------------
export DOCKER_BUILDKIT=1
log "Building images one at a time (limits peak memory)"
for svc in backend-migrate backend frontend website; do
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" build "$svc"
done
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" --profile seed build backend-seed

log "Starting the stack"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d

# ----------------------------------------------------------------------------
# 5. Wait for the backend to become healthy
# ----------------------------------------------------------------------------
log "Waiting for the backend to report healthy (migrations apply first)"
for i in $(seq 1 60); do
  state=$(docker inspect -f '{{.State.Health.Status}}' itemba_r_backend_prod 2>/dev/null || echo starting)
  echo "  [$i] backend: $state"
  [ "$state" = "healthy" ] && break
  sleep 5
done
if [ "$(docker inspect -f '{{.State.Health.Status}}' itemba_r_backend_prod 2>/dev/null)" != "healthy" ]; then
  echo "Backend did not become healthy. Logs:" >&2
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" logs --tail=80 backend backend-migrate >&2
  exit 1
fi

# ----------------------------------------------------------------------------
# 6. Seed (idempotent: group, 3 companies, roles, admin user)
# ----------------------------------------------------------------------------
log "Seeding base data (admin + org structure)"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" --profile seed run --rm backend-seed

# ----------------------------------------------------------------------------
# 7. Nightly backup cron + one backup now
# ----------------------------------------------------------------------------
log "Installing nightly database backup (02:30) -> /opt/itemba-backups"
mkdir -p /opt/itemba-backups
# Unquoted heredoc so ${REPO_DIR} is baked in now; runtime vars are escaped (\$).
cat > /usr/local/bin/itemba-backup.sh <<BKEOF
#!/usr/bin/env bash
set -euo pipefail
cd "${REPO_DIR}"
STAMP=\$(date -u +%Y%m%d-%H%M%S)
OUT="/opt/itemba-backups/itemba_r-\${STAMP}.sql.gz"
docker compose --env-file .env.production -f docker-compose.production.yml exec -T postgres \\
  pg_dump -U itemba_user itemba_r | gzip > "\$OUT"
# keep the last 14 days
find /opt/itemba-backups -name 'itemba_r-*.sql.gz' -mtime +14 -delete
echo "backup -> \$OUT"
BKEOF
chmod +x /usr/local/bin/itemba-backup.sh
CRON_TMP="$(mktemp)"
crontab -l 2>/dev/null | grep -v 'itemba-backup.sh' > "$CRON_TMP" || true
echo "30 2 * * * /usr/local/bin/itemba-backup.sh >> /var/log/itemba-backup.log 2>&1" >> "$CRON_TMP"
crontab "$CRON_TMP"
rm -f "$CRON_TMP"
/usr/local/bin/itemba-backup.sh || log "first backup will run on the next cron tick"

# ----------------------------------------------------------------------------
# Done
# ----------------------------------------------------------------------------
log "Relaunch complete."
cat <<DONE

  Stack is up. Verify:
    curl -fsS https://api.${DOMAIN}/api/v1/health   (after DNS + TLS settle)
    docker compose --env-file ${ENV_FILE} -f ${COMPOSE_FILE} ps

  Log in at:  https://app.${DOMAIN}
    admin@${DOMAIN} / see SEED_ADMIN_PASSWORD in ${ENV_FILE}
    CHANGE THIS PASSWORD IMMEDIATELY.

  Secrets are in ${REPO_DIR}/${ENV_FILE}  — back that file up now.
  Nightly DB backups -> /opt/itemba-backups (02:30 UTC, 14-day retention).
DONE
