#!/usr/bin/env bash
#
# ITEMBA-R one-shot relaunch / provisioning script for a fresh Ubuntu droplet.
#
#   - installs Docker + the compose plugin (if missing)
#   - adds swap so the two Next.js builds don't OOM on a small droplet
#   - generates fresh production secrets ON THIS HOST and writes ./.env
#     (secrets never leave the droplet; ./.env is gitignored)
#   - builds + starts the full production stack (migrations run automatically)
#   - runs the idempotent seed (group/companies/roles/admin user)
#   - installs a nightly pg_dump backup cron + takes one backup now
#
# Usage (from the repo root, as root or a sudo user):
#   DOMAIN=itembagrouptz.com bash deploy/relaunch/deploy.sh
#
# Re-running is safe: existing .env + secrets are preserved, the stack is
# rebuilt/updated, and the seed upserts.

set -euo pipefail

# ----------------------------------------------------------------------------
# Config (override via env: DOMAIN=... ACME_EMAIL=... bash deploy/relaunch/deploy.sh)
# ----------------------------------------------------------------------------
DOMAIN="${DOMAIN:-itembagrouptz.com}"
ACME_EMAIL="${ACME_EMAIL:-info@${DOMAIN}}"
COMPOSE_FILE="docker-compose.production.yml"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_DIR"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

gen_secret() { openssl rand -base64 48 | tr -d '\n/+=' | cut -c1-48; }

# ----------------------------------------------------------------------------
# 1. Docker + compose plugin
# ----------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker Engine + compose plugin"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg openssl git
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
else
  log "Docker already installed: $(docker --version)"
fi

# ----------------------------------------------------------------------------
# 2. Swap (so the Next.js builds don't OOM on a 4 GB droplet)
# ----------------------------------------------------------------------------
TOTAL_RAM_MB=$(free -m | awk '/^Mem:/{print $2}')
if [ "${TOTAL_RAM_MB:-0}" -lt 7000 ] && [ ! -f /swapfile ]; then
  log "Adding 4 GB swap (RAM is ${TOTAL_RAM_MB} MB)"
  fallocate -l 4G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=4096
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

# ----------------------------------------------------------------------------
# 3. Generate .env with fresh secrets (only if it does not already exist)
# ----------------------------------------------------------------------------
if [ ! -f .env ]; then
  log "Generating fresh production secrets -> .env"
  cat > .env <<ENVEOF
# Generated by deploy/relaunch/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# SECRET — never commit. Back this file up somewhere safe (a password manager).

# --- Database ---
POSTGRES_DB=itemba_r
POSTGRES_USER=itemba_user
POSTGRES_PASSWORD=$(gen_secret)

# --- Redis ---
REDIS_PASSWORD=$(gen_secret)

# --- Auth / crypto (each must be distinct) ---
JWT_ACCESS_SECRET=$(gen_secret)
JWT_REFRESH_SECRET=$(gen_secret)
TWO_FACTOR_ENCRYPTION_KEY=$(gen_secret)
REFRESH_TOKEN_PEPPER=$(gen_secret)
APP_ENCRYPTION_KEY=$(gen_secret)
JWT_ACCESS_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# --- Domain / TLS (Caddy) ---
ACME_EMAIL=${ACME_EMAIL}
APP_HOST=app.${DOMAIN}
API_HOST=api.${DOMAIN}
WEBSITE_HOST=${DOMAIN}
WEBSITE_WWW_HOST=www.${DOMAIN}

# --- App URLs ---
FRONTEND_URL=https://app.${DOMAIN}
APP_URL=https://app.${DOMAIN}
CORS_ORIGIN=https://app.${DOMAIN}
NEXT_PUBLIC_API_URL=https://api.${DOMAIN}/api/v1
NEXT_PUBLIC_WEBSITE_URL=https://${DOMAIN}
BACKEND_INTERNAL_URL=http://backend:3001/api/v1

# --- Misc ---
JOB_WORKER_ENABLED=true

# --- Optional integrations (fill in if/when needed) ---
# SMTP_HOST=
# SMTP_PORT=587
# SMTP_USER=
# SMTP_PASS=
# SMTP_FROM=
# MPESA_CONSUMER_KEY=
# MPESA_CONSUMER_SECRET=
# MPESA_SHORTCODE=
# MPESA_PASSKEY=
ENVEOF
  chmod 600 .env
  log ".env created. BACK IT UP — these secrets cannot be recovered."
else
  log ".env already exists — leaving it untouched"
fi

# ----------------------------------------------------------------------------
# 4. Build + start the stack (migrations run via the backend-migrate one-shot)
# ----------------------------------------------------------------------------
export DOCKER_BUILDKIT=1
log "Building images one at a time (limits peak memory)"
for svc in backend-migrate backend frontend website; do
  docker compose -f "$COMPOSE_FILE" build "$svc"
done

log "Starting the stack"
docker compose -f "$COMPOSE_FILE" up -d

# ----------------------------------------------------------------------------
# 5. Wait for the backend to become healthy
# ----------------------------------------------------------------------------
log "Waiting for the backend to report healthy (migrations apply first)"
for i in $(seq 1 60); do
  state=$(docker inspect -f '{{.State.Health.Status}}' itemba_r_backend_prod 2>/dev/null || echo starting)
  echo "  [$i] backend: $state"
  [ "$state" = "healthy" ] && break
  sleep 5
done
if [ "$(docker inspect -f '{{.State.Health.Status}}' itemba_r_backend_prod 2>/dev/null)" != "healthy" ]; then
  echo "Backend did not become healthy. Logs:" >&2
  docker compose -f "$COMPOSE_FILE" logs --tail=80 backend backend-migrate >&2
  exit 1
fi

# ----------------------------------------------------------------------------
# 6. Seed (idempotent: group, 3 companies, roles, admin user)
# ----------------------------------------------------------------------------
log "Seeding base data (admin + org structure)"
docker compose -f "$COMPOSE_FILE" run --rm backend-migrate npm run db:seed

# ----------------------------------------------------------------------------
# 7. Nightly backup cron + one backup now
# ----------------------------------------------------------------------------
log "Installing nightly database backup (02:30) -> /opt/itemba-backups"
mkdir -p /opt/itemba-backups
# Unquoted heredoc so ${REPO_DIR} is baked in now; runtime vars are escaped (\$).
cat > /usr/local/bin/itemba-backup.sh <<BKEOF
#!/usr/bin/env bash
set -euo pipefail
cd "${REPO_DIR}"
STAMP=\$(date -u +%Y%m%d-%H%M%S)
OUT="/opt/itemba-backups/itemba_r-\${STAMP}.sql.gz"
docker compose -f docker-compose.production.yml exec -T postgres \\
  pg_dump -U itemba_user itemba_r | gzip > "\$OUT"
# keep the last 14 days
find /opt/itemba-backups -name 'itemba_r-*.sql.gz' -mtime +14 -delete
echo "backup -> \$OUT"
BKEOF
chmod +x /usr/local/bin/itemba-backup.sh
( crontab -l 2>/dev/null | grep -v itemba-backup.sh; echo "30 2 * * * /usr/local/bin/itemba-backup.sh >> /var/log/itemba-backup.log 2>&1" ) | crontab -
/usr/local/bin/itemba-backup.sh || log "first backup will run on the next cron tick"

# ----------------------------------------------------------------------------
# Done
# ----------------------------------------------------------------------------
log "Relaunch complete."
cat <<DONE

  Stack is up. Verify:
    curl -fsS https://api.${DOMAIN}/api/v1/health   (after DNS + TLS settle)
    docker compose -f ${COMPOSE_FILE} ps

  Log in at:  https://app.${DOMAIN}
    admin@itemba.local / ChangeMe!123   <-- CHANGE THIS PASSWORD IMMEDIATELY

  Secrets are in ${REPO_DIR}/.env  — back that file up now.
  Nightly DB backups -> /opt/itemba-backups (02:30 UTC, 14-day retention).
DONE
